### ISSUE TITLE
Bandwith and  sensor names problems

### ISSUE THREAD

**Issue by hadarsonego** [neuralfraud/grafana-prtg#10]
Hey,
I have annoying issue - 
I have 4 Windows servers that i monitor there Memory usage , for the example i have a server called DC-C01 and server that called Filesrv , the sensor on the filesrv called "% free Filesrv" and on the DC-C01 it's called "% free DC-C01" - (PRTG names)
![image](https://cloud.githubusercontent.com/assets/17380427/13202361/a8d764ba-d8a0-11e5-8b9b-9c2034f02f4b.png)
![image](https://cloud.githubusercontent.com/assets/17380427/13202364/be4bcf98-d8a0-11e5-94dc-4b223e7d1c88.png)
On the grafana server all the names starts to mismatch and all the servers sensors are called  "% free Filesrv"   - 

![image](https://cloud.githubusercontent.com/assets/17380427/13202374/23be5d0a-d8a1-11e5-9a58-12e2139d2af5.png)

![image](https://cloud.githubusercontent.com/assets/17380427/13202376/362f9634-d8a1-11e5-9d0f-bc1f3f075e51.png)

It happens with all servers and this is an example for only one mismatch but all servers are saying "% free Filesrv" , i did refresh to the Datasource 10 times , i removed the sensors and created them again, i restarted both servers.
Any ideas? 
Thanks!

**Comment by neuralfraud** [comment]
The fact that those names are actually in PRTG is quite strange... i've never seen those. the channels are always downtime, available percent, and available memory (bytes). please try the current release and comment if this is still an issue.

thanks

**Comment by neuralfraud** [comment]
Please upgrade. The master branch solves that, and it looks like you're using a very old version, Make sure you're using Grafana 3.0 or newer and get the code from Master.

Additionally, the development branch has lots of kick ass new features, and is reasonably stable :)
