### ISSUE TITLE
Units incorrect

### ISSUE THREAD

**Issue by wlolato** [neuralfraud/grafana-prtg#102]
Hi,

My graph on grafana displays units in Tbps, that is incorrect.

![image](https://user-images.githubusercontent.com/39568904/40446393-72b8a406-5ea5-11e8-94dd-a2e2e4b0e3a2.png)

PRTG displays correct traffic in Mbits/S

![image](https://user-images.githubusercontent.com/39568904/40446459-ad59e9da-5ea5-11e8-8082-5bf8ff141579.png)

What can a fix to resolve this ?

Thanks.

**Comment by ktngoykalolo** [comment]
Hi,
any update on this ? I have the same issue

**Comment by Zxurian** [comment]
It looks like the response from PRTG may be off?
This is the raw XML from the grafana request:
```xml
   <item>
    <datetime>6/25/2018 12:10:14 PM</datetime>
    <datetime_raw>43276.6737732870</datetime_raw>
    ...
    <value channel="Traffic In (volume)" channelid="0">32 MByte</value>
    <value_raw channel="Traffic In (volume)" channelid="0">33635451.0000</value_raw>
    <value channel="Traffic In (speed)" channelid="0">0.90 Mbit/s</value>
    <value_raw channel="Traffic In (speed)" channelid="0">112118.1700</value_raw>
    <value channel="Traffic Out (volume)" channelid="1">85 MByte</value>
    <value_raw channel="Traffic Out (volume)" channelid="1">89027133.0000</value_raw>
    <value channel="Traffic Out (speed)" channelid="1">2.37 Mbit/s</value>
    <value_raw channel="Traffic Out (speed)" channelid="1">296757.1100</value_raw>
    ...
    <coverage>100 %</coverage>
    <coverage_raw>0000010000</coverage_raw>
   </item>
```

the volume channel matches up to it's raw, but the speed channel doesn't look like the calculations are matching up.

If I view the sensor directly on PRTG, and view the table as XML, the raw value shown matches what is received by Grafana. so the problem might be with PRTG?

**Comment by hungdohuy** [comment]
Hi,

I notice the same issue here,
On PRTG:
![image](https://user-images.githubusercontent.com/1115723/47896396-f36d6800-de9f-11e8-9b01-3cb4a233d2b0.png)


But on Grafana:
![image](https://user-images.githubusercontent.com/1115723/47896378-dd5fa780-de9f-11e8-9abf-98a43417222b.png)

Max on PRTG is 10,450 kbit/s
Max on Grafana is 1153615 (don't know what is the unit actually) not match either with bits/s or anything

**Comment by biloriaj** [comment]
How could we solve this issue? I am having the same problem when I pull out the data from the PRTG and try to graph in the Grafana. Any comments that it could help to overcome this issue or any workaround?

**Comment by tehSMK** [comment]
there is a multiplier field in the grafana dashboard when you choose PRTG Datasource.

**Comment by biloriaj** [comment]
Hi, TehSMk. I could not find any field, could you please share more details about this?
Thank you in advance.
Jesus Viloria

**Comment by tehSMK** [comment]
@biloriaj
you should have an option when you select your datasource.

![datasource](https://user-images.githubusercontent.com/35838113/59270690-6ae35100-8c52-11e9-884b-b7eef2db17ed.PNG)

**Comment by biloriaj** [comment]
Hi, TehSMK. Thank you for your comments. unfortunately, I do not have the option, please take a look:

 
![grafana multiplier](https://user-images.githubusercontent.com/50921917/59298622-88afb680-8c50-11e9-9d60-ab9a17eb3098.PNG)

**Comment by biloriaj** [comment]
guys! any comments about this issue I am having, 
thanks in advance. 
Jesus Viloria

**Comment by neuralfraud** [comment]
Prtg bandwidth values are in Bytes/s. 

The dev branch has a feature which allows you to specify a multiplier for the data if you wish to scale it down to bits, kbytes, etc.

**Comment by RamiroCarlos** [comment]
Hi, thanks for your work, it definitely helped us to solve the problem, cuted the work in half. We fixed the units in (data rate) bits/sec(SI) ignoring the raw values that are in Bytes, next we Transform the value from Bytes to Bits throught the multiplication of 8
![values](https://user-images.githubusercontent.com/78658554/196932675-4a00e552-2b9e-4383-b93a-f2997eafebad.png)
