### ISSUE TITLE
Query fields only showing asterisks 

### ISSUE THREAD

**Issue by SamuelmAsh** [neuralfraud/grafana-prtg#103]
Hi there, i've added two prtg servers as datasources and checked the network activity when adding them, when i run the query generated in the url of my browser it returns what i would expect about the devices on that PRTG server. However when trying to create a dashboard all i get are asterisks in the Group/Probe/Device fields etc

Any tips?

The logins worked fine on the older version of grafana and have adequate rights. Latest PRTG and Grafana. cheers
sam

**Comment by mpcrossley** [comment]
This keeps happening to me too. :(

Any tips? Eventually "Root" showed up under group, but nothing else... Only asterisks.

**Comment by SamuelmAsh** [comment]
This appears to be something within the datasource that takes the passhash. When adding the datasource it connects fine and ports the passhash through however when trying to add a graph the query it sends to PRTG is formatted 

Request URL: http://172.20.7.135:3000/api/datasources/proxy/1/table.json username=GrafanaAPI&passhash=[object%20Object]&content=groups&count=9999&columns=o.....


&passhash=[object%20Object]

Looks to be the issue, something to do with field sanitation ? 

Cheers
Sam

**Comment by mpcrossley** [comment]
I noticed that as well when I changed it to "browser" connection setting.

Possible that Grafana changed the way it's passing objects to the plugin?

**Comment by mpcrossley** [comment]
So I've tried hacking it to use a static hash, but I suspect I need to do something else to actually make it "stick" in grafana...

I don't think it's as simple as editing the .js file. 

@neuralfraud  - any ideas? Help? :)

**Comment by mpcrossley** [comment]
Looks like something broke between 5.0.3 and 5.0.4.

I installed both on a test system, and 5.0.3 works fine. 5.0.4 has the javascript object being passed instead of the passhash

**Comment by mpcrossley** [comment]
Hmmm - so, I just tried it on a new machine, and every version (including 4.6.3) has the same issue, whereas my other PC (which I don't have access to currently) does not have this problem.

Weird... I will keep testing.

**Comment by moonbotIO** [comment]
Hey guys - had the same issue. I upgraded from 5.1.3 to 5.2.0-beta1, and that fixed it for me. It's possible a reinstall of 5.1.3 would have fixed it, but I didn't test that prior to overwriting 5.1.3.

**Comment by SamuelmAsh** [comment]
Hmm strange i have Grafana v5.1.3 (commit: 087143285) which was certainly not working to start with. Since changing the users in the datasource however this started to work. Which doesnt make any sense as the outgoing query wouldnt know the response. 

I'd suggest ensuring the PRTG account you use is in the PRTG Administrators group and contains no punctuation. I saw this issue with Grafana.API but non with the PRTGDashAPI username. 

Sorry for the really terrible debugging :)

**Comment by mpcrossley** [comment]
Welp, I think I got it figured.

The "apiuser" account I created was a regular, read-only user.

Experimenting, it looks like the API user needs to be admin & read-write (looks like PRTG won't let you create someone who is read only in the admins group).

**Comment by Maxhawkgt** [comment]
I have the same issue with only "*" showing up in Group, Host, Sensor, and Channel. I have only one user defined in PRTG and it's the PRTG Admin account which is part of the PRTG Administrators group.

I'm on Grafana v5.3.4 (commit: 69630b9) and PRTG 18.4.45.1898+. In Grafana Data Sources the Save & Test returns a green box with checkmark and "PRTG API version: 18.4.45.1898+" so it seems to be happy.

Any thoughts on what I can try?

**Comment by neuralfraud** [comment]
Latest build uses secureJsonData to store passhash. Try it out, you'll probably have to re-enter the passhash.
