### ISSUE TITLE
Bandwidth problem

### ISSUE THREAD

**Issue by hadarsonego** [neuralfraud/grafana-prtg#11]
Hey,
I have a Bandwidth sensor on my PRTG that gives the traffic from the outside (Internet) to my organization.
![image](https://cloud.githubusercontent.com/assets/17380427/13202566/b232c44e-d8a7-11e5-8e10-7e4a5063e8f5.png)

Now it's 72,000 kbit\s , when i add this sensor to the grafana i'm not getting the correct value - 
![image](https://cloud.githubusercontent.com/assets/17380427/13202575/03e7787a-d8a8-11e5-9239-7d81ac5cbf88.png)

I tried to change it to kbit\s and still not the correct value - 
![image](https://cloud.githubusercontent.com/assets/17380427/13202579/2e425cf2-d8a8-11e5-88d9-6ee1dd005045.png)

I looked at the XML that the PRTG API gives , and it looks like it's the correct value , i thinks it's something in the grafana , i don't know what.
Any idea? 
Thanks!

**Comment by yossiv** [comment]
same issue for me.

**Comment by neuralfraud** [comment]
Seems some conversion going on. The numbers in grafana are in bytes, not bits. 

The values reported in prtg are converted to kbits/sec, so If I'm looking at my office to datacenter WAN link and see for 11:22:28 AM that the traffic in (speed) channel is "2198 kbits/sec" and divide that by 8 I  get 274.75 and that matches the number grafana sees. The correct scale I think should be datarate > bytes/sec

I'll review the code just to make sure I'm not doing something braindead in there, but if you change it to bytes/sec, it should be accurate.

Thanks!

**Comment by SlodeSoft** [comment]
How i can convert in Kbit/s ?

**Comment by SlodeSoft** [comment]
It's possible to keep data rate of PRTG ? I don't want the conversion  :(

**Comment by neuralfraud** [comment]
I'm going to amend this by saying, at least on my sFlow sensors, that it is actually bits/sec. Closing.
