### ISSUE TITLE
Multiple lines from single query

### ISSUE THREAD

**Issue by Yakelixir** [neuralfraud/grafana-prtg#110]
![screen shot 2018-08-03 at 2 49 10 pm](https://user-images.githubusercontent.com/5784897/43660289-27710a76-9724-11e8-96a5-9deace44f74e.png)

I'm seeing multiple lines from in Grafana with a single query for a single channel. HTTP sensor with downtime and load time channels and I'm queryng downtime. Im wondering how I'm getting three series when I only see one set of data in PRTG.

Thanks in advance. Cheers!

**Comment by palidin74** [comment]
I am seeing the same thing there at random. For example I setup a Grafana panel checking something as simple as a ping time in PRTG. It works just fine for an hour or sometimes a day then all of a sudden the same query is returning two values. I will see 1.1ms pingtime and a second 1.3ms pingtime yet the PRTG sensor only has one value.

**Comment by palidin74** [comment]
Diggint into this deeper it appears it has something to do with the naming. You will notice that the sensors where this issue occurs are named the same. It seems the PRTG plugin somehow ignores the device name all of a sudden and is pulling sensor data that is named the same in the same group etc. I resolved this for me by naming the specific sensor so its different than all other sensors and the issue went away.
