### ISSUE TITLE
Channel Templating Issue

### ISSUE THREAD

**Issue by Yakelixir** [neuralfraud/grafana-prtg#111]
Looks like there is a issue with the way that we are doing channel templating. I'm seeing the following...

PRTG API ARROR
"Channel Template query is malformed"

This is from a 'channel:sensor=$sensor'

![image](https://user-images.githubusercontent.com/5784897/43688575-63729fa8-98b9-11e8-929d-f8d386358802.png)

**Comment by Yakelixir** [comment]
Standard progression of templating as seen below... Nothing interesting in my mind however at this basic level it was worth noting here.

![image](https://user-images.githubusercontent.com/5784897/43688584-92367684-98b9-11e8-868e-8f523f1ceba1.png)

**Comment by codecharacter** [comment]
@Yakelixir Did you ever find a solution for the channel variable?

**Comment by viruz82** [comment]
Closed with no answer. Very helpful. Thanks for nothing. @Yakelixir

**Comment by liam-ng** [comment]
any hint would be appreciated
