### ISSUE TITLE
Raw query to table.json error

### ISSUE THREAD

**Issue by jeedee5** [neuralfraud/grafana-prtg#114]
I am runnin Grafana 5.2.2, and PRTG API 18.3.43.2323.
When I query with RAW, I get "Request error" in Grafana when using table.json as URI. 

When running the request manualy in a browser, I am getting an output
https://hostname/api/table.json?content=sensors&columns=device,sensor,status,message,downtimesince&filter_status=4&filter_status=5
![grafana3](https://user-images.githubusercontent.com/4850169/44574368-834cb280-a789-11e8-82ca-f8939a26c889.jpg)

However, when using this request in Grafana, I get a request error.
![grafana2](https://user-images.githubusercontent.com/4850169/44574221-06b9d400-a789-11e8-9d81-85355c933373.jpg)

I have also tested the template dashboard, and the system status with getstatus.htm in the URI looks to be working, however, the data doesn't seems to be consistent
![grafana1](https://user-images.githubusercontent.com/4850169/44574112-c3f7fc00-a788-11e8-96ce-46dc8e3b8bd9.jpg)

**Comment by jeedee5** [comment]
Restarted the grafana services... now the json query works....
The issue with the amount of messages remains however...

**Comment by neuralfraud** [comment]
Real late here, but perhaps that's a weird Grafana issue... i took my example dashboard there, removed the columns and replaced them and it seems to be ok.. 

Also this version (6) seems to support color/rules for string values as well, so that's pretty nice.  Closing;
