### ISSUE TITLE
Is the developer of this wonderfull plugin still alive?

### ISSUE THREAD

**Issue by olsonnn** [neuralfraud/grafana-prtg#116]
and if so, able/ willing to spend some time on it to fix some issues?
Would be great! Thanks!

**Comment by SamuelmAsh** [comment]
I think its safe to say we are on our own making this stable once more !

**Comment by neuralfraud** [comment]
Please open an issue for an actual issue that is not already open. If the issue you have exists, please add your comment there. 

..and yes I am alive :)
