### ISSUE TITLE
Plugin PRTG \ Grafana Alert

### ISSUE THREAD

**Issue by mamontr** [neuralfraud/grafana-prtg#120]
Hi!
I need your help.
I use prtg pugin for Grafana. In my case I need to configure the alerts. BUT grafana does not respond to the settings correctly. Tell me how to make grafana work correctly with alerts or accept alerts from PRTG (which are already configured).

Thank you a lot!

**Comment by neuralfraud** [comment]
Use PRTG for Alerts :)
