### ISSUE TITLE
Table with json data does not update in TEXT and RAW mode [Fix]

### ISSUE THREAD

**Issue by Sonnenstrahl** [neuralfraud/grafana-prtg#123]
#85 
#51 
#114
#115 

I noticed that applying the following changes to ```/dist/PRTGAPIService.js``` fixes the json data problem:
Remove [Line 113 - 115]
``` js
          if (this.inCache(options.url)) {
            return this.getCache(options.url);
          } else {
```
Remove [Line 158]
``` js
        }
```
Your tables should now update in realtime.

**Comment by olsonnn** [comment]
Since we applied this patch, the load on our prtg has increased a lot.
Rolled back but it seems the modified js file is cached now in browsers... 
Be carefull with this 'patch'

**Comment by AnimaBe** [comment]
Anyone have another fix for this?

**Comment by forever765** [comment]
@neuralfraud I also have the same question.
The problem seriously affects the use in the production environment, can you give priority to it?
Thank you very much!

**Comment by neuralfraud** [comment]
If you dont want to use cache you can always disable it.

There is a reason its there though.

**Comment by neuralfraud** [comment]
I am sorry you did that; plain bad advice. That line just adds data to the cache and then never uses it, its effectively disabling the cache with extra steps.

**Comment by forever765** [comment]
@neuralfraud  can you fix this bug fundamentally?
