### ISSUE TITLE
Anyone here ?

### ISSUE THREAD

**Issue by ced455** [neuralfraud/grafana-prtg#125]
Hello, i am looking for a replacement for grafana + prtg since this plugins is pretty much dead,
i need to constantly reboot the grafana server to make my graph works after changes....

**Comment by neuralfraud** [comment]
There really isn’t one. I realize this isn’t the best plugin in the world, and Paessler has made a few improvements to built in dash boarding, though. I’m no longer a PRTG customer (no fault of theirs!) and have not been keeping up with it - sorry. If anyone wants to chip in to help develop it, that would be great. This was last tested with 3.x and early versions of 4.x. Grafana is browser driven and your browser does cache a lot of the data. Restarting should only need to happen if you change the configuration of the PRTG service API I.e. credentials.

**Comment by ced455** [comment]
yup you are right, it crash also with the "explore functionality, need to reboot when using it"
thank you anyway for everything you have done on this plugin, it was good fun and still is when you know how to not make it crash :)

**Comment by neuralfraud** [comment]
@ced455 btw just poking around with grafana on my laptop, When you change or delete objects in PRTG, you have to refresh your Grafana browser/tab because the results from the group/device/sensor queries get cached.
