### ISSUE TITLE
Display count of down sensors in a Table Panel

### ISSUE THREAD

**Issue by LiamEponym** [neuralfraud/grafana-prtg#128]
Hi everyone,
I'm struggling on how to display the number of down sensors in a table.
Oddly enough, displaying Up sensors and Warning sensors is possble thanks to "Upsens" and "Warnsens" but "Downsens" and "Totalsens" don't work, why is that ?

My query is "id=14376&tabid=0&filter_type=ping" with "getstatus.htm" URI

**Comment by neuralfraud** [comment]
@LiamEponym in the visualization options, make sure you're using JSON Data and for columns, select "Alarms". I don't see a "Totalsens" field anywhere in the JSON. Downsens is "Alarms"

**Comment by neuralfraud** [comment]
also closing because while very obtuse and clunky, it is really not a plugin issue. Thank you.
