### ISSUE TITLE
Discontinued project

### ISSUE THREAD

**Issue by tormodhope** [neuralfraud/grafana-prtg#129]
Is there anyone with skills that want to take over this development? I see in another issue that the project owner says its dead.

Last commit is over 2 year old.

**Comment by neuralfraud** [comment]
Ive been waiting two years for someone to offer that. Are you offering to help? Do you have an environment that can be used for testing these issues? I dont have access to any of that any more.

**Comment by tormodhope** [comment]
Hi,

I do have an environment with a PRTG install and Grafana running development version of this plugin.
But there is more that needs to be done for it to be perfect.

**Comment by palidin74** [comment]
neuralfraud - We are a small town WISP but we have quite the server infrastructure with PRTG and Grafana. I can setup and provide any test environment you need. This plugin is a lifesaver for us and for others I am sure. We would be glad to help if you still want to push development.

**Comment by neuralfraud** [comment]
@palidin74 shoot an email over to nf@<myusername>.net if you're still interested. I'm reviewing some issues and testing with PRTG as of 10/19 and Grafana 6.4.3.
