### ISSUE TITLE
Duplicate Device Names Cause Error

### ISSUE THREAD

**Issue by ptcfast2** [neuralfraud/grafana-prtg#13]
I'm assuming this is an issue with logic somewhere, and it's the same thing that I thought was the issue with the Sensor Factory sensor but it's an actual global problem.

Let's say you structure PRTG into groups that use the actual device names as the group names. The devices within those groups are actually named in accordance with what the device contains (Ethernet Interfaces for example). This is a pretty way to build a sunburst for a large device such as a UCS chassis as an example.

When you have a device with the same name in different groups (either on purpose or by accident) the plugin does not work properly. You'll get a bunch of N/A's in Grafana. Would this a Grafana problem or plugin problem? If it's Grafana well crap. If it's the plugin, would it be possible to differentiate same device names via group location and make sure something unique is supplied to Grafana?

![image](https://cloud.githubusercontent.com/assets/16966701/14265881/ecd25964-fa78-11e5-94a9-afbfa99136ed.png)

**Comment by neuralfraud** [comment]
So the way this works is as you select group, device, sensor, channel, you end up with the known device ID, the sensor ID and the channel name, which is text. It shouldn't be causing issues, but that doesn't mean there isn't one. 

I think this should be something I can test and resolve.

**Comment by neuralfraud** [comment]
Update: in the current release now, all groups are deduplicated. That means that in this case, you'll see the UCS chassis from both groups when you select "Operability". I have 2 cluster probes and 3 remote probes, and it became very frustrating, so I copied the way the grafana-zabbix plugin worked :) Hope this fixes the problem and thank you for your support/patience!
