### ISSUE TITLE
Update Installation Page, Step 5, to Indicate the Passhash is the Needed Credential

### ISSUE THREAD

**Issue by PDQDakota** [neuralfraud/grafana-prtg#133]
I can't seem to find a way to do this myself as when I clone the repo the wiki doesn't make it over to my fork.

Would it be possible to update the installation guide to indicate the passhash is the required credential?

Instead of:
`Step 5: Provide information - choose a simple name, e.g., "PRTG" and provide the API URL and credentials.`

Use:
`Step 5: Provide information - choose a simple name, e.g., "PRTG" and provide the API URL and passhash of the user from the account page of PRTG.`

I'd do this myself but I can't seem to figure out how to fork the wiki, I can clone it but that does no good for submitting a pull request (to my knowledge!).

**Comment by neuralfraud** [comment]
Done.
