### ISSUE TITLE
Grafana 6.4.0 Breaks Tables

### ISSUE THREAD

**Issue by ThomasRunting** [neuralfraud/grafana-prtg#135]
Just be warned Grafana 6.4.0 breaks the tables. 6.3.6 works fine tho

**Comment by Shadow00Caster** [comment]
Can confirm, any chance of this getting updated?

**Comment by neuralfraud** [comment]
@ThomasRunting @Shadow00Caster I am Using Grafana 6.4.3 right now and tables appear to work, can you provide a screenshot?

**Comment by Shadow00Caster** [comment]
@neuralfraud I just upgraded from 6.4.1 to 6.4.3 and tables are working now, so there must have been something in in an update after 6.4.1 that fixed/changed something.
