### ISSUE TITLE
Merge Development into Master

### ISSUE THREAD

**Issue by SoarinFerret** [neuralfraud/grafana-prtg#137]
For awhile now, its been recommended to everyone in the comments of these issues to simply use the development branch for the use of the multiplier.

I know that this project is no longer being actively maintained, which is fine, but could we get the development branch merged into master, and listed as the main release?

I suppose the only concern there would be giving the appearance of this being actively maintained by increment of version number.

**Comment by neuralfraud** [comment]
done.
