### ISSUE TITLE
Graph not working when opening from Different TimeZone 

### ISSUE THREAD

**Issue by yossiv** [neuralfraud/grafana-prtg#14]
Graph not working when opening from Different TimeZone 
when trying to load a graph that pulling data from PRTG.
example GMT+8 area trying to open from its browser Graph that taken from the PRTG (located on TimeZone GMT+3 its not working. 
i need to do last 6 hours and than it will start show me data of the last hour

**Comment by neuralfraud** [comment]
So then it's using browser time literally, it seems. I'm working on a release that supports Grafana 3.1 right now, but I will see if there's something I can do to ensure the data works regardless of timezone on your browser. Thanks for the report!

**Comment by neuralfraud** [comment]
So, this is kind of silly, but PRTGs dates are represented in local time. For this to work across timezones, I can add an option to the datasource setup page... which I could then convert the from, to dates to UTC and then to the timezone of the server ...which might work.

**Comment by yossiv** [comment]
That's might be great


-------- Original Message --------

**Comment by neuralfraud** [comment]
Do you have remote probes with unique timezones, or is the entire server under a single timezone?

**Comment by yossiv** [comment]
Hi.  any solution for this ?

**Comment by yossiv** [comment]
@neuralfraud  ok i found a workaround solution which i think is the best to solve this issue.
i created dedicated user on the PRTG  for the API access from the GRAFANA
and on the user setting under the timezone change it to the relevant timezone the grafana will run.
i tested it , and it works great!
![image](https://cloud.githubusercontent.com/assets/19520218/18902435/ad40fcba-855b-11e6-9fe1-931cdf55ef7c.png)

**Comment by yurividal** [comment]
Hi. I am facing this exact issue. The problem is that my dashboard is accessed by people in different parts of the world. The only ones that see the time correct are the ones in California (because the API user is set to California time in PRTG). All the other people see the data shifted, and therefore, wrong. This workarround is not a fix.... can this issue be reopened?

**Comment by cmtk** [comment]
I hate to help resurrect a 4 year old thread, but I have the same issue as well, with Grafana showing data shifted when viewed from other timezones.

Looking through the PRTG API, it looks like most things have UTC options, but not everything unfortunately.

- /status.json returns `jsClock`, a unix timestamp (UTC) 👍
- /historicdata.json returns `datetime_raw`, [an Excel decimal datetime](https://kb.paessler.com/en/topic/1313-how-do-i-translate-prtg-timestamp-values-format-to-normal-time-format) (in UTC) 👍😕
- /table.json returns `datetime` via `columns` as an Excel decimal datetime (in UTC) 👍😕
- /historicdata.json queries require start and end dates... in the PRTG user's local time. 🚫

One possible solution could be to just require the PRTG user used for API access to have its timezone set to UTC. At least until PRTG provides a UTC option for query parameters.
