### ISSUE TITLE
Weird issue with 4.04 plugin Data missing in graphs timeframe >24hours

### ISSUE THREAD

**Issue by olsonnn** [neuralfraud/grafana-prtg#140]
version 4.0.3 works fine but version 4.0.4 shows gaps in data when time frame is longer then 24hours.
zooming in will still show the data...

Reverted back to 4.0.3, all fine again

**Comment by forever765** [comment]
same question

**Comment by neuralfraud** [comment]
The live data api is supposed to provide up to 40 days of data...i will look into this. Thanks!

**Comment by olsonnn** [comment]
Example of what happens:
[https://drive.google.com/open?id=1zCsQ2xHN4v3XN5RHhRHhUZhrTvdGIav5](url)

**Comment by neuralfraud** [comment]
Fixed. Git pull if you've cloned, or grab a new download from Master branch. 

Thank you.

**Comment by olsonnn** [comment]
Thanks for fixing this one! really appreciated!

**Comment by oparekh** [comment]
Hi. 
I used PRTG 19.4.53.1912 with Grafana 4.6.6 and PRTG plugin 4.0.4.  The plugin doesn't convert the datetime in the latest version correctly which means the graph is not showing on Grafana at all.

When I now use the PRTG plugin 4.0.0 the graph is showing correctly without any problems.

**Comment by neuralfraud** [comment]
should have been fixed in the latest commit;
https://github.com/neuralfraud/grafana-prtg/commit/d39d6b35d5244ffc91887ed6e2ae66d54a56b14a

Why? I changed the data fetch method from XML to JSON; the JSON output no
longer includes the raw numeric date, rather it's formatted as a string.
