### ISSUE TITLE
Compatibility PRTG

### ISSUE THREAD

**Issue by SlodeSoft** [neuralfraud/grafana-prtg#15]
Hi all,

I have a question ? 

What is the older version of PRTG to work with this Plug-in ?

Thanks in advance ?

**Comment by neuralfraud** [comment]
If you're asking what is the oldest version of PRTG known to work, I would say anything that implements the REST API should be OK. I developed this on 15.2 and it works through the current 16.3 release as well.

I cannot guarantee it'll work with older versions as they may have missing features.

**Comment by SlodeSoft** [comment]
ok thanks for your answer !
