### ISSUE TITLE
PRTG showing more than 100% Utilization

### ISSUE THREAD

**Issue by reuvygroovy** [neuralfraud/grafana-prtg#152]
We have an issue where PRTG returns over 100% utilization for a line. Of course this is an issue with PRTG. Nevertheless, is there a smart method in the code by which we can "cap" the maximum value displayed to always be 100?

**Comment by angela-d** [comment]
Are you using the Bar Gauge visualization?

If so, there's a value mapping you might be able to use to cap it.

Also, under the **Field** column, there's a mix/max option:
![bargauge](https://user-images.githubusercontent.com/33108490/74204310-42c04d80-4c38-11ea-8915-e1b7da9f6d59.png)

**Comment by reuvygroovy** [comment]
Hi Angela,
for some reason that did nothing. So instead we just modified the JavaScript of the plugin, so that if the values received were over 100 we just capped them at 100. Not sure if there was a misunderstanding on our part, or the plugin (which is still in beta) doesn't work, but we achieved our requirement.

Thanks!
