### ISSUE TITLE
Pulling correct data from sensor

### ISSUE THREAD

**Issue by TheSteemer** [neuralfraud/grafana-prtg#159]
Installed and configured Grafana to connected with PRTG. I have a few devices that pull data fine, but its pulling the incorrect data. How do we go about getting the correct info returned to the graph?

For example on the attached picture. The prtg probe I want to return Speed. Graphana is grabbing volume. In the Channel there’s nothing other than in/out/total. In the xml it appears to be grabbing the _raw data.

I have posted multiple places with no response for assistance: https://community.grafana.com/t/prtg-pulling-incorrect-stat/26493

`  "response": "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\r\n  <histdata totalcount=\"359\" listend=\"1\">\r\n   <prtg-version>20.1.55.1775</prtg-version>\r\n   <item>\r\n    <datetime>3/3/2020 8:32:53 AM</datetime>\r\n    <datetime_raw>43893.5645039931</datetime_raw>\r\n    <value channel=\"Traffic Total (volume)\" channelid=\"-1\">9,775,865 KB</value>\r\n    <value_raw channel=\"Traffic Total (volume)\" channelid=\"-1\">10010486257.0000</value_raw>\r\n    <value channel=\"Traffic Total (speed)\" channelid=\"-1\">1,332,067 kbit/s</value>\r\n    <value_raw channel=\"Traffic Total (speed)\" channelid=\"-1\">166508420.7751</value_raw>\r\n    <value channel=\"Traffic In (volume)\" channelid=\"0\">4,401,161 KB</value>\r\n    <value_raw channel=\"Traffic In (volume)\" channelid=\"0\">4506788406.0000</value_raw>\r\n    <value channel=\"Traffic In (speed)\" channelid=\"0\">599,706 kbit/s</value>\r\n    <value_raw channel=\"Traffic In (speed)\" channelid=\"0\">74963213.6727</value_raw>\r\n    <value channel=\"Traffic Out (volume)\" channelid=\"1\">5,374,705 KB</value>\r\n    <value_raw channel=\"Traffic Out (volume)\" channelid=\"1\">5503697851.0000</value_raw>\r\n    <value channel=\"Traffic Out (speed)\" channelid=\"1\">732,362 kbit/s</value>\r\n    <value_raw channel=\"Traffic Out (speed)\" channelid=\"1\">91545207.1025</value_raw>\r\n    <coverage>100 %</coverage>\r\n    `

**Comment by ohmar** [comment]
Which build are you using? Some improvements have been made to the latest build on the master branch.

**Comment by TheSteemer** [comment]
Grafana version 6.6.2
PRTG Plugin version 4.0.3

**Comment by ohmar** [comment]
Upgrade your plugin. 4.0.3 is a few years old. Unfortunately, you'll have to upgrade manually since the updated version is not available on grafana.com.

**Comment by TheSteemer** [comment]
Any idea where to get the newer files? Repository here only has 4.0.3

**Comment by ohmar** [comment]
Just clone or [download the master branch](https://github.com/neuralfraud/grafana-prtg/archive/master.zip).

**Comment by TheSteemer** [comment]
ohmar, thank you. After the install I am able to see all of the channels. Have a great week!
