### ISSUE TITLE
Plugin broken in Grafana 6.7.1 

### ISSUE THREAD

**Issue by jonare77** [neuralfraud/grafana-prtg#163]
Anyone know anything about this issue. My whole Granfana are not displaying any date from PRTG.

https://github.com/grafana/grafana/issues/22956

**Comment by ldti** [comment]
It's not working with anything higher than 6.6.2

**Comment by MDaugaardDK** [comment]
Anyone know when this issue will be fixed? We are using Grafana 6.7.1 and nothing works :-/

**Comment by jonare77** [comment]
Damn I didt notice this before upgrading.

**Comment by jeremyroche-er** [comment]
looks like 6.7.2 fixes the issue.

**Comment by MDaugaardDK** [comment]
no luck here.... maybe im doing something wrong?
When im trying to query something, the result is just: ""Not sure how to handle this request. Request: content=devices&count=9999&columns=objid,device,group,probe,tags,active,status,message,priority""

**Comment by fecsmith** [comment]
Just updated from 6.7.1 to 6.7.2 and plugin has begun working again for me

**Comment by jonare77** [comment]
Fixed or atleast working in 6.7.2
