### ISSUE TITLE
PRTG Grafana Dashboard No data

### ISSUE THREAD

**Issue by mafer0410** [neuralfraud/grafana-prtg#165]
Hello, I am new to using dashboards in Grafana with PRTG, I tried to create one, but this one is not shown in the graph, it says: No data.
![no data](https://user-images.githubusercontent.com/51204835/80534923-3907d580-895d-11ea-899f-7fd566709791.PNG)

**Comment by ldti** [comment]
You might want to begin here:
https://github.com/angela-d/brain-dump/tree/master/grafana-prtg

**Comment by mafer0410** [comment]
thanks
