### ISSUE TITLE
Dont found plugin PRTG Grafana

### ISSUE THREAD

**Issue by lodbrokk** [neuralfraud/grafana-prtg#172]
Hello friends, I currently have grafana v7.0.3 and PRTG 20.2.59.1689 installed, I proceeded with the configuration according to the indicated manual but when creating the datasource when sending the test it stays as loading and does not work, if you could help me with recommendations or What would be the possible problem attached screenshots.

![prtconsulta2](https://user-images.githubusercontent.com/67158698/85148110-5cd8f080-b215-11ea-8b48-3935af743041.PNG)
![prtgconulta](https://user-images.githubusercontent.com/67158698/85148113-5e0a1d80-b215-11ea-857c-7903617e355a.PNG)

**Comment by angela-d** [comment]
[Try these instructions](https://github.com/angela-d/brain-dump/blob/master/grafana-prtg/setup.md) - a hybrid of neuralfraud's wiki + notes from a recent setup

**Comment by lodbrokk** [comment]
Thank you very much for your help, it worked perfectly
