### ISSUE TITLE
Problems with table panel

### ISSUE THREAD

**Issue by joachimd90** [neuralfraud/grafana-prtg#177]
Hi.. I have for some time now tried to get my table view for PRTG alarm to work, but I can't seem to make it happen! 

I have multiple graphs, gauges and stats up and running without any problems. But it's look like the query arent picking up any data, only result I get when trying is a heading "BLAH" and 2 bracket { }. When I hoover the brackets, I get "Object: No Properties". This is something new, because on my prod-server, I are actually getting data under objects but arent able to do anything with them..

I am running Grafana Enterprise 7.1.5 with Grafana PRTG plugin 4.0.3/4.0.4 (Tried both of them) 
Have correct setup in datasources, since I getting other data from PRTG. 

What I am trying to do: 

Query mode: RAW
Query URI: table.json 
Query String: content=columns&sensors=device,sensor,status,message,downtimesince&filter_status=4&filter_status=5

Are there someone with the same problem, or someone who had the same problem but solved somehow? 

Thanks!

**Comment by craftzneko** [comment]
Hey @joachimd90 i logged this same problem logged in 5 days ago https://github.com/neuralfraud/grafana-prtg/issues/176
