### ISSUE TITLE
Beta 3.0 Installation

### ISSUE THREAD

**Issue by suckamucka** [neuralfraud/grafana-prtg#18]
In testing beta 3.0, I dropped jasonlashua-prtg-datasource in public/app/plugins/datasource directory
I was able to add the plugin, but it fails to display the configuration of the plugin where we can add login information and URL to the PRTG server.

**Comment by suckamucka** [comment]
Ok, I had to also copy files from dist and place them in the root of jasonlashua-prtg-datasource

**Comment by neuralfraud** [comment]
It goes in the data/plugins folder, not the public/app/plugins/datasource

I added that to the readme.md for the 3.0 branch. There's still a lot to be
done so I will be sure to make that more clear!

**Comment by suckamucka** [comment]
I saw that in the readme.md, however grafana-3.1.1 doesn't have a data/plugins folder.
The only things in the data folder are: logs, sessions

**Comment by neuralfraud** [comment]
When you start for the first time grafana will create those directories.
It's kind of weird. If in doubt, check the Ini file.

Thanks!

**Comment by suckamucka** [comment]
Very strange. The directory was not created for me automatically.
I created the data/plugins directory and placed jasonlashua-prtg-datasource inside.
Still not able to activate the plugin

**Comment by neuralfraud** [comment]
Even after removing from app/plugins/datasource? It should show up in the
startup console/log output.

Are you using Linux or Windows to run grafana? I haven't tested on Linux
and I'm not sure what the default data directory is.

**Comment by suckamucka** [comment]
Grafana on Windows.

**Comment by suckamucka** [comment]
Do I still need to copy everything out of the dist folder and into the root of the data/plugins/jasonlashua-prtg-datasource directory?

**Comment by neuralfraud** [comment]
Assuming you downloaded the entire 3.0 branch, and you opened the .zip in explorer, you literally only need to drag the "jasonlashua-prtg-datasource" folder into the X:\Grafana-3.1.1\data\plugins directory.

**Comment by suckamucka** [comment]
I downloaded the whole zip. Once I extract I have [MainDirectory.png]
then in src I have [srcDirectory.png]
and finally in dist I have [distDirectory.png] 

Is this correct?


![maindirectory](https://cloud.githubusercontent.com/assets/5890876/18105053/fe45dc30-6ecb-11e6-96ec-57733994856c.png)
![srcdirectory](https://cloud.githubusercontent.com/assets/5890876/18105121/42f40104-6ecc-11e6-853d-5ed57ce2f97b.png)
![distdirectory](https://cloud.githubusercontent.com/assets/5890876/18105128/46926dc8-6ecc-11e6-8aa0-5bbd2ae5affb.png)

**Comment by ptcfast2** [comment]
Try GRAFANA FOLDER\bin\data\plugins

Mine was automatically created in there for whatever reason. Put it there and it worked like a charm.

**Comment by neuralfraud** [comment]
Because grafana is kind of stupid. It uses the base directory from the
execution context!

So I launch mine from the app folder...if you launch from bin, that
explains it. Thanks man!

**Comment by suckamucka** [comment]
Yes, I launched from the bin directory as well. I will move it back to \bin\data\plugins and try again

**Comment by suckamucka** [comment]
Able to add a graph but the values are showing "NaN" however in PRTG the values are showing correctly.

**Comment by yossiv** [comment]
How about Linux ubuntu?
i put the directory on \var\lib\grafana\plugins and it didnt work .

**Comment by neuralfraud** [comment]
@suckamucka :
#1 - are you using the grafana proxy feature? (you should be) 
#2 - per the installation instructions, did you update the PRTG registry key with the necessary header (see section regarding CORS)

**Comment by neuralfraud** [comment]
@yossiv depends on the settings in your grafana configuration. I can't say - I've not yet run it on Linux.

**Comment by yossiv** [comment]
@neuralfraud no matter. i moved my Grafana to run on Windows as a services. 
thanks :+1:

**Comment by suckamucka** [comment]
1. yes I have the proxy feature enabled
2. yes the registry has been updated with the necessary header

Just to be certain, I rebuilt the PRTG server and added Grafana and the Grafana-PRTG plugin.
Same results where graph is showing NaN

**Comment by ptcfast2** [comment]
I've found that depends on the sensor. I also get NaN and "object undefined" errors on some sensor types now that were working previously. Might want to create a separate issue for this.

**Comment by yossiv** [comment]
@ptcfast2 
https://github.com/neuralfraud/grafana-prtg/issues/20

**Comment by SlodeSoft** [comment]
I work on Linux Ubuntu, i try different solution :+1: 

- /usr/share/grafana/public/app/plugins/datasource - chown -R grafana:grafana
- /var/lib/grafana/plugins/
- /usr/share/grafana/data/plugins (create data/plugins)

Nothings works :(

**Comment by jtenniswood** [comment]
Just tried the beta with the grafana docker image, but couldn't get the datasource plugin to work. Shame, it sounds like a great product

**Comment by SlodeSoft** [comment]
There is just a problem with bandwith for me :(, and of course it's the most important for me XD !
But great job neuralfraud do you work on a new version ?

**Comment by suckamucka** [comment]
Has anyone found a workaround for bandwidth showing up as NaN?

**Comment by SlodeSoft** [comment]
Same

**Comment by jwlar** [comment]
Same bandwidth issue here

**Comment by beardpapi** [comment]
Same issue here

**Comment by neuralfraud** [comment]
Original Parent installation issue:

On windows, or if improperly configured, Grafana will create the data directory RELATIVE to execution path.
for instance, if you start C:\grafana-4.1.2\bin\grafana-server.exe from the folder C:\grafana-4.1.2, the data directory will be created as C:\grafana-4.1.2\data - as expected.

Bandwidth sensors show up correctly. The datasource always looks for a channel definition with the word "(speed)" next to it. This is a behavior quirk of PRTG. 

All bandwidth values are in bits per second, use the "data rate > bits / sec" option in your panels.
