### ISSUE TITLE
401 - Unauthorized during API configuration

### ISSUE THREAD

**Issue by Arkios** [neuralfraud/grafana-prtg#19]
I'm getting a "401: Unauthorized" error when trying to connect to the PRTG API.

I have Grafana and PRTG sitting on the same system, with PRTG using port 80 for access and Grafana using port 8080. 

When I try to connect to PRTG from Grafana I keep getting the 401 error regardless of whether I use the account password or the Passhash. I've attached a screenshot of my config, am I missing something? I feel like I've tried every combination imaginable and just cannot get the API to connect. I've also tried using the default prtgadmin account (with password & passhash) with no luck.

![unauthorized error](https://cloud.githubusercontent.com/assets/21694873/18184689/1c24cd5e-704f-11e6-9f82-8e88bdd37abf.PNG)

**Comment by Arkios** [comment]
This has been solved, I only changed two things:

1) Quit using Microsoft Edge, started trying using Firefox
2) Reset password for the apiuser account to **NOT** include any special characters. (Don't need to use the Passhash)

**Comment by i3laze** [comment]
Apparently, a passhash is also not a plain text user password, but it's hash:
https://www.paessler.com/manuals/prtg/my_account_settings
