### ISSUE TITLE
Missing multiplier field with plugin install

### ISSUE THREAD

**Issue by mspencerl87** [neuralfraud/grafana-prtg#190]
I saw that the development branch was merged to main. But for the life of me can't seem to understand why i'm missing the multiplier field so I can make proper conversions of metrics. Any ideas?
![multiplier](https://user-images.githubusercontent.com/47121646/151416710-e0ebed00-7b29-4c64-863c-c1aaa7a6ef04.png)

**Comment by d4n3sh** [comment]
@mspencerl87  this might help https://github.com/neuralfraud/grafana-prtg/issues/184

**Comment by mspencerl87** [comment]
@d4n3sh Thanks. I didn't realize that Grafana didn't have 4.4 "Latest" from their repository... lol Thanks
