### ISSUE TITLE
Implement support for sensor status singleStat panels

### ISSUE THREAD

**Issue by neuralfraud** [neuralfraud/grafana-prtg#2]
Singlestat panels can be useful for displaying the general status of a sensor. PRTG uses several numeric codes to denote Up, Down, Down (Acknowledged), and others. 

Status is part of a sensor, not a channel within a sensor, so it requires a slightly different query. perhaps add a checkbox option? 

Caveats: would require you to manually create a "value to text" mapping... but you're sysadmins and you already know what the status codes are.. so no big deal, right?

**Comment by richter-p** [comment]
+1 on sensor status implementation. What I'd need before I could use this awesome plugin to replace my existing PRTG maps would be an "all down sensors" table.

**Comment by neuralfraud** [comment]
Pardon the late response.... version 4.0  (currently in the Development branch) addresses that and more. It is now possible to do just this. For instance, create a table and select "Text" mode, then:
Value From: sensor
Property: Status
Filter Property: /^[^U]/ (filters all the UP sensors) - and much more. check it out!

![image](https://user-images.githubusercontent.com/8482103/28255625-5efa9b9e-6a87-11e7-870d-5f7415c05d5f.png)
