### ISSUE TITLE
Beta 3.0 Linux Issue

### ISSUE THREAD

**Issue by bin000001** [neuralfraud/grafana-prtg#22]
I do see from previous threads that official support for linux has not been provided and/or tested. However, any information you may be able to provide would be excellent. I have added the repository into the linux directory /var/lib/grafana/plugins/jasonlashua-prtg-datasource. When I restarted grafana, the plugin did show up. When I entered the credentials for the prtg data source I did not receive any errors.

The issue comes into play when I start to create dashboards. When I create a new dashboard, I actually do see the prtg core, probes and sensors as options for selection. So it seems that grafana is able to make a connection to prtg and get that information. However, grafana doesn't actually graph any of the data. Any tips/ideas on what I can do to make this work. Any files I can edit? Or any logs I can look at for errors? Would kindly appreciate any information you can provide.

![prtgattach](https://cloud.githubusercontent.com/assets/19859529/18450902/e6b7f148-7902-11e6-99d0-3f9749931bc5.PNG)

**Comment by neuralfraud** [comment]
Did you miss the group selection...? it needs to know that in order to query the API

**Comment by neuralfraud** [comment]
This issue should be resolved if you are using Grafana 3.0+ and the current release, https://github.com/neuralfraud/grafana-prtg/archive/master.zip
