### ISSUE TITLE
PRTG HTTPS Support

### ISSUE THREAD

**Issue by evanjfraser** [neuralfraud/grafana-prtg#23]
Hello,

Thank you so much for writing this plugin, it really fills a valuable niche I think.

Do you know if the plugin supports HTTPS connectivity to PRTG?  I can't seem to get it to work.

However when I set up a dummy PRTG install on HTTP it worked just fine.

Cheers!

**Comment by richter-p** [comment]
Should work just fine, my instance is only accessible via https and the plugin works. Any chance you didn't set the regedit-tweak?

**Comment by neuralfraud** [comment]
HTTPS works fine indeed.
