### ISSUE TITLE
Followed your installation but cant find PRTG in list of data sources

### ISSUE THREAD

**Issue by blarrkan** [neuralfraud/grafana-prtg#25]
Hi,
I´m running  Grafana v3.1.1 and followed your guide. Sadly I´m unable to see PRTG in available datasources.

Any tips?

**Comment by jorgedlcruz** [comment]
Hi,
Trying copy the content inside the folder dist on the root folder itself, so inside jasonlashua-prtg-datasource

Is working for me, Grafana on Linux, with the content on this folder:
**/usr/share/grafana/public/app/plugins/datasource/jasonlashua-prtg-datasource**

so the content of the folder is:
root@tig-monitor:/usr/share/grafana/public/app/plugins/datasource/jasonlashua-prtg-datasource# ls -la
total 176
drwxr-xr-x  6 root root  4096 Sep 26 18:27 .
drwxr-xr-x 13 root root  4096 Sep 26 18:16 ..
-rw-r--r--  1 root root  8865 Sep 26 18:27 datasource.js
-rw-r--r--  1 root root 11945 Sep 26 18:27 datasource.js.map
drwxr-xr-x  4 root root  4096 Aug 28 02:37 dist
-rw-r--r--  1 root root  1328 Aug 28 02:37 gruntfile.js
drwxr-xr-x  2 root root  4096 Sep 26 18:27 img
-rw-r--r--  1 root root  1724 Sep 26 18:27 module.js
-rw-r--r--  1 root root  1198 Sep 26 18:27 module.js.map
-rw-r--r--  1 root root  1084 Aug 28 02:37 package.json
drwxr-xr-x  2 root root  4096 Sep 26 18:27 partials
-rw-r--r--  1 root root   591 Sep 26 18:27 plugin.json
-rw-r--r--  1 root root  2604 Sep 26 18:27 PRTAPICore.js
-rw-r--r--  1 root root  1433 Sep 26 18:27 PRTAPICore.js.map
-rw-r--r--  1 root root 17548 Sep 26 18:27 PRTGAPIService.js
-rw-r--r--  1 root root 27884 Sep 26 18:27 PRTGAPIService.js.map
-rw-r--r--  1 root root 10722 Sep 26 18:27 query_ctrl.js
-rw-r--r--  1 root root 14789 Sep 26 18:27 query_ctrl.js.map
-rw-r--r--  1 root root   137 Sep 26 18:27 README.md
drwxr-xr-x  4 root root  4096 Aug 28 02:37 src
-rw-r--r--  1 root root  6821 Sep 26 18:27 xmlparser.js
-rw-r--r--  1 root root  7978 Sep 26 18:27 xmlparser.js.map
-rw-r--r--  1 root root  3787 Sep 26 18:27 XMLtoJSON.xsl

This is working for me

**Comment by blarrkan** [comment]
Ok, then something is strange. I only have the following files,
drwxr-xr-x  3 root root  4096 Sep 28 14:01 .
drwxr-xr-x 13 root root  4096 Sep 28 14:01 ..
-rw-r--r--  1 root root 13877 Sep 28 14:01 api_wrapper.js
-rw-r--r--  1 root root  6406 Sep 28 14:01 datasource.js
-rw-r--r--  1 root root   567 Sep 28 14:01 directives.js
drwxr-xr-x  2 root root  4096 Sep 28 14:01 partials
-rw-r--r--  1 root root   357 Sep 28 14:04 plugin.json
-rw-r--r--  1 root root  7914 Sep 28 14:01 query_ctrl.js
-rw-r--r--  1 root root  6404 Sep 28 14:01 xmlparser.js

Also the plugin.json had wrong format.
Like   "pluginType": "datasource", instead of   "type": "datasource",

When I changed it to type I can see it in Grafana, but I get xml errors.

**Comment by jorgedlcruz** [comment]
If you have Grafana 3.x you should had downloaded this:
https://github.com/neuralfraud/grafana-prtg/archive/3.0.zip

Try with that package :)

**Comment by blarrkan** [comment]
Thanks! Totally missed that I could choose different branch. Now Grafana can add a PRTG source with success :)
Just waiting for data to show up now :)

**Comment by jwlar** [comment]
Is this issue closed then?

**Comment by anthraxau** [comment]
Im having the same issue.
PRTG does not show in the Type when im trying to add a data source.

**Comment by neuralfraud** [comment]
Download here: https://github.com/neuralfraud/grafana-prtg/archive/master.zip

This is the updated/current working version for the current Grafana release.
