### ISSUE TITLE
Update to 4.0

### ISSUE THREAD

**Issue by neuralfraud** [neuralfraud/grafana-prtg#27]
lodash has been updated with grafana 4.0

_.map function seems to not work any more. Check lodash dependency

**Comment by yossiv** [comment]
Hi @neuralfraud  Any progress with this Project..?

**Comment by darinarrick** [comment]
I'm also interested in this. I'm install Grafana 4.1.1+Graphite+Etc. to provide a dashboard for our IT department. We use PRTG for monitoring and alerting, and we want to use it as our main source of data for the dashboard. But I've been unable to get your plugin to work successfully. Any help would be appreciated. Thanks!

**Comment by darinarrick** [comment]
I may have some time to glance at the plugin and see why it doesn't work under 4.x. Is there any documentation I should read about Grafana plugin development?

**Comment by neuralfraud** [comment]
Update regarding this: Code now working with Grafana 4.1.2; I was
improperly using a bunch of "legacy" javascript conventions and need to
update those to use ES6 syntax ($q undefined, etc). Sorry for such a long
delay.

I have to update the html partials so that they look right, and then I can
at least focus on fixing some of the other issues now that the main
compatibility barrier has been solved ;)

I'll have a commit by the weekend for you guys. Thank you for your patience!

**Comment by yossiv** [comment]
Woow thanks!
That’s really great news.
Appreciate your Time

**Comment by darinarrick** [comment]
@neuralfraud : No problem! Thank you for looking at it! Let me know if there's anything I can do to help.

**Comment by neuralfraud** [comment]
As promised, I updated the 3.0 branch and merged it back into master, so now you can just clone/download from master!

Everything seems to be working OK. 

The metric query editor has been changed - but you should find it to be quite usable. It uses a type-completion system now.

If you have multiple remote probes and multiple similarly named groups, the behavior will be to deduplicate the list of groups. If you therefore have two "Network Infrastructure" groups, for instance, then you should see the devices within both groups as you type.

**Comment by yossiv** [comment]
thanks!
so this code works also with version 4 ?

**Comment by neuralfraud** [comment]
Yup. Using it with 4.1.2 right now.

**Comment by darinarrick** [comment]
Excellent news! I'm about to install it into our Grafana 4.1.2 installation. I'll let you know how it works.

**Comment by darinarrick** [comment]
I've installed it successfully, but when I try to add a metric, I seem unable to see the sensors. Our PRTG setup is basically:

Group Main
-Probe HQ
--Group Networking
---Switch
----Sensor
-----Channel1
-----Channel2
---Switch2
----Sensor
-----Channel1
-Probe DC
--Group Networking
---Switch
----Sensor
-----Channel1
etc.

But in the Metrics tab I only see Group, Host, Sensor, and Channel. Group gets populated with the main group name fine, but everything else is only "*" with the exception of channel which has both "*" and "!". It looks like the datasource isn't recursing through the tree or something.

We're thinking of temporarily creating another top-level group and then just using factory sensors to point to channels in other groups. But that's a pretty clunky workaround, IMO.

Is this a bug? Any ideas or suggestions? And thanks again for your work!

**Comment by neuralfraud** [comment]
At the very least, the device has to be populated for sensors to show up.

When you clear the input or start typing, you will see "type ahead"
suggestions.

If all you see in the channel is asterisk and !, then the items haven't
loaded.

Everything typed in is case sensitive, so when you see a typeahead item
that matches, use that item.

**Comment by darinarrick** [comment]
I assumed all the above. The Group box populates; it shows the top group name and "*". None of the other fields either populates or matches anything when I type into them.

**Comment by darinarrick** [comment]
In a standard installation, where could I look for logs of what your datasource is attempting to do?

**Comment by neuralfraud** [comment]
If you want to see what's going on, open the developer console and monitor
the network activity, you'll see every request

Grafana may be logging depending on how you've configured it.

**Comment by darinarrick** [comment]
So I'm getting an Unauthorized response. I've fed it the username and passhash multiple times. It pulls the version correctly; if I mess up the pashhash, that fails as it should. But the datasource adds correctly, then it's not pulling anything now.

I've double-checked the user in PRTG. Case is correct in the user name (all lower). It's set to a read-only user. Etc. The only thing I don't understand in the request below is the passhash. Isn't it supposed to be the actual passhash? Any ideas?

GET https://dcvbtmon/api/table.json?username=grafana&passhash=[object%20Object]&content=devices&columns=objid,device,group&filter_group=Infrastructure

Potentially unhandled rejection [31] Unknown error: <HTML><BODY><B>Unauthorized</B></BODY></HTML> (WARNING: non-Error used)
(anonymous) @ boot.b8fccc44.js:5
f @ boot.b8fccc44.js:5
i @ boot.b8fccc44.js:5

**Comment by neuralfraud** [comment]
@darinarrick Which version of the code are you using?
 (timestamp of files in jasonlashua-prtg-datasourc/dist)

What is on line 106 of dist/PRTGAPIService.js ?
It should read:

           var queryString = 'username=' + this.username + '&passhash=' + this.passhash + '&' + params;

And what version of grafana? I've only tested with 4.1.2.



The test function works s

**Comment by neuralfraud** [comment]
@darinarrick Please See issue #31 - I'm closing this one. 3 people so far have reported the same issue, though it's magically cleared up for at least one. So far I'm not sure what it could be. I've been unable to reproduce it,
