### ISSUE TITLE
I have multiple probes, can't select the right one

### ISSUE THREAD

**Issue by JoooostB** [neuralfraud/grafana-prtg#28]
In PRTG I have a probe per region (North-America, Europe, AFOS etc.), I need to visualize multiple devices from different probes. Unfortunately, I'm unable to select a probe in grafana-prtg. Is there any other way?

EDIT: I found a workaround, by changing the JSON I can request my wanted scope. It won't be shown right under Metrics, but it works. Will set it to solved now :)

**Comment by neuralfraud** [comment]
@JoooostB btw, in the current release, a group that exists in multiple probes can be selected, and all devices will show up. further, you do not need to choose a group, simply typing a string in the device box will start showing matches. this should take care of that issue.
