### ISSUE TITLE
Support Sending Alerts metrics 

### ISSUE THREAD

**Issue by yossiv** [neuralfraud/grafana-prtg#33]
although Prtg makes a good altering. i would like to to know if there is an option to make 
that the Grafana Alert will work with the PRTG plugin .
test result shows its now working

![image](https://cloud.githubusercontent.com/assets/19520218/23200935/cff2179c-f8df-11e6-9a94-078bdc385371.png)

** is there any option to make a donation. 
im really appreciate your work . i would like to donate 🥇

**Comment by neuralfraud** [comment]
I'll see what I can do!

If anyone wants to donate, https://PayPal.me/jaylashua

Thanks

**Comment by neuralfraud** [comment]
Ok I don't know if this is immediately possible. This requires me to build a module in Go and essentially compile it into grafana-server.exe, so first I'll have to develop a module, try to compile it and see if it works, and then submit a pull request to grafana/grafana and then hope they include it, and then you could download/build from source or wait until next build :)

for now, though, i'll see what i can get working.

**Comment by neuralfraud** [comment]
Just an update, I'm not going to be writing a Go module. my reason being is that PRTG on its own merits has perfectly fine alerting and notifications, so grafana really doesn't need it. I'm going to be focusing my efforts on metric functions after version 4.0 (in Development) is complete and merged into the master branch.
