### ISSUE TITLE
PRTG logo url not valid

### ISSUE THREAD

**Issue by miquelMariano** [neuralfraud/grafana-prtg#36]
Hi all, I detect that the url logo image is not valid and logo does not look correctly

![image](https://cloud.githubusercontent.com/assets/12425938/23506076/a782e4f4-ff46-11e6-9190-753e8c3c58d4.png)

URL points to /jasonlashua-prtg-datasource/img/PRTGlogo.png but PRTGlogo.png not exist into this path

Is necessary rename file or modify code

![image](https://cloud.githubusercontent.com/assets/12425938/23506136/f9dbeee4-ff46-11e6-87d7-0f10146fe4b2.png)

![image](https://cloud.githubusercontent.com/assets/12425938/23506246/991cc1ea-ff47-11e6-86b6-64b52ddac196.png)

Regards!

**Comment by neuralfraud** [comment]
Fixed in development branch. :)

**Comment by miquelMariano** [comment]
Thx!
