### ISSUE TITLE
Need help with configuration

### ISSUE THREAD

**Issue by saymonaraujo** [neuralfraud/grafana-prtg#38]
Hello, 

I am not geting to configure.
Whem i hit save & test apears:
undefined: undefined

Can anyone help me ?
that's my email: saymon.onl@gmail.com

I realy need help guys.

Thank you.

**Comment by saymonaraujo** [comment]
Nobody can help me ?

**Comment by ruudmens** [comment]
In the most cases it's an authentication issue. Did you use the password hash instead of the normal password?

**Comment by neuralfraud** [comment]
I'm sorry to not respond to this, but configuration is pretty well explained in the wiki. In any case, here's an example:

![image](https://user-images.githubusercontent.com/8482103/28255681-177b7058-6a88-11e7-8a60-557419ed9fb6.png)
