### ISSUE TITLE
SNMP Traffic sensors problem

### ISSUE THREAD

**Issue by dmayan** [neuralfraud/grafana-prtg#39]
Hi,

When I try to get traffic data from SNMP traffic sensors, I'm getting the value divided by ten.

For example: I'm currently at 1.031.366.613 bits/s on my core router, reported bt PRTG, but the plugin gets 103.136.661 bits/s.

What do you need in order to debug this?

Many thanks!

**Comment by dmayan** [comment]
Nevermind, found that PRTG reports the raw vale to the plugin, wich is in bytes/sec. Is there any way of altering o doing the math to display it in other units??

thanks again,

**Comment by saymonaraujo** [comment]
Hey, can you help me on integration ? 
I am geting one error: undefined: undefined

saymon.onl@gmail.com

Apreciate

Saymon Fernandes

**Comment by vbtadmin** [comment]
I'm wondering the same thing. I have a sensor that pulls traffic data using SNMP into PRTG. When I look at the channel for traffic, I see four rows: Downtime, Traffic in, Traffic Out, and Traffic Total. I also see multiple columns, including Last Value {Volume}, Last Value (Speed), Minimum [speed], and Maximum [speed].

The PRTG datasource lets me choose the row, but not the column. Therefore, when I choose Traffic Total, I get Traffic Total/Last Value (Volume). This does correctly show me the amount of data being sent over a time period, but doesn't show me the speed, which is what I'm really after.

Can another field be added to the Metrics tab to allow the selection of the column? This may not be the only use case where someone would want to do something like this, either.

Thanks!

**Comment by darinarrick** [comment]
I'm wondering the same thing. I have a sensor that pulls traffic data using SNMP into PRTG. When I look at the channel for traffic, I see four rows: Downtime, Traffic in, Traffic Out, and Traffic Total. I also see multiple columns, including Last Value {Volume}, Last Value (Speed), Minimum [speed], and Maximum [speed].

The PRTG datasource lets me choose the row, but not the column. Therefore, when I choose Traffic Total, I get Traffic Total/Last Value (Volume). This does correctly show me the amount of data being sent over a time period, but doesn't show me the speed, which is what I'm really after.

Can another field be added to the Metrics tab to allow the selection of the column? This may not be the only use case where someone would want to do something like this, either.

Thanks!

**Comment by darinarrick** [comment]
Example:

API Call: /api/table.xml?content=channels&output=html&columns=name,+lastvalue_&id=12345

This call returns all columns. Currently, the first column is selected by default by the datasource. But you can see that there's a second column, with speed in kbits/sec. I'd like to be able to select columns in the Metrics tab.

<form id="form_">
<table cellspacing=0 class=" table hoverable channels" id="table_">
<colgroup><col class="col-name"/><col class="col-lastvalue"/><col class="col-lastvalue"/></colgroup>

<thead class="headerswithlinks"><tr><th>Channel</th><th>Last Value (volume)</th><th>Last Value (speed)</th></tr></thead>
<tbody><tr class="odd"><td class="col-name">Downtime</td><td class="col-lastvalue"></td><td class="col-lastvalue">&nbsp;</td></tr>
<tr class="even"><td class="col-name">Traffic In</td><td class="col-lastvalue">313,752 KByte</td><td class="col-lastvalue">42,845 kbit/s</td></tr>
<tr class="odd"><td class="col-name">Traffic Out</td><td class="col-lastvalue">152,452 KByte</td><td class="col-lastvalue">20,818 kbit/s</td></tr>
<tr class="even"><td class="col-name">Traffic Total</td><td class="col-lastvalue">466,204 KByte</td><td class="col-lastvalue">63,663 kbit/s</td></tr>
</tbody></table></form>

**Comment by ruudmens** [comment]
> When I try to get traffic data from SNMP traffic sensors, I'm getting the value divided by ten.
I got the same issue. There should be a way to correct this. Some sensors are going ok, for example, one UPS temp reports 260 degrees instead of 26, other UPS returns the normal 26 degrees.

**Comment by neuralfraud** [comment]
Traffic sensors are usually bytes/sec. The "display" values are converted, however the raw values are typically bytes. I believe this issue was addressed, closing.
