### ISSUE TITLE
Issue with adding as datasource

### ISSUE THREAD

**Issue by solaris187** [neuralfraud/grafana-prtg#40]
Pulled the latest update of the plugin today. When trying to add to grafana as a new datasource I receive the following errors:

Plugin Error
(SystemJS) XHR error (404 Not Found) loading http://192.168.135.71:3000/public/app/plugins/datasource/jasonlashua-prtg-datasource/module.js?bust=1490011140149 Error: XHR error (404 Not Found) loading http://192.168.135.71:3000/public/app/plugins/datasource/jasonlashua-prtg-datasource/module.js?bust=1490011140149 Error loading http://192.168.135.71:3000/public/app/plugins/datasource/jasonlashua-prtg-datasource/module.js

Which makes sense since the module.js file its trying to find is in fact in http://192.168.135.71:3000/public/app/plugins/datasource/jasonlashua-prtg-datasource**/dist/**module.js

**Comment by solaris187** [comment]
solved by logging out of grafana and back in after adding the datasource.

**Comment by Saviger** [comment]
I am getting the same issue, have tried the logout-in method. I tried a copy of the .js files it's complaining about to the directory it's looking for them in, but am getting a 505:Bad Gateway error.
