### ISSUE TITLE
Query Examples

### ISSUE THREAD

**Issue by xxKryptonite** [neuralfraud/grafana-prtg#50]
I was just wondering if you could post the queries that you used to create the "Templated Dash 1" template that is in the screenshot.  For example, the "PRTG System Status" row.  I have been trying to figure it out and can not get it to work.  Thanks

**Comment by neuralfraud** [comment]
Rename this file to a .json and import w/grafana

[Templated Dash 1-1501286287605.txt](https://github.com/neuralfraud/grafana-prtg/files/1184490/Templated.Dash.1-1501286287605.txt)

**Comment by xxKryptonite** [comment]
Thanks.  I appreciate your work on this!

**Comment by danfoxley** [comment]
@neuralfraud Thanks for your Grafana Plugin, is a breath of fresh air to the RRD/MRTG graphs in PRTG.  I downloaded the Templated Dash 1, and a lot of the panels and queries to build them didn't load into Grafana.  Any chance you could share key screen shots showing the query sections of the panels? I'm having trouble seeing how the table data displays in Grafana.

Thanks,
Dan
