### ISSUE TITLE
JSONData Table with ActiveAlarms won't update

### ISSUE THREAD

**Issue by JohnH77** [neuralfraud/grafana-prtg#51]
I see your Sreenshots with Active Alarms Table that is useful for us. I have created a Table with raw Query an JSON Data
URI: table.json 
Query String: content=sensors&columns=objid,downtimesince,device,sensor,lastvalue,status,message,priority&filter_status=5&filter_status
![image](https://user-images.githubusercontent.com/30649081/28861567-c68777c8-7761-11e7-86be-8d0a5023a553.png)
![image](https://user-images.githubusercontent.com/30649081/28861757-92d5708c-7762-11e7-8109-0d89851b451f.png)

The Data in the Table won't update. I see just the Data that were created with the Table. 

Did i do something wrong or how do you create the Active Alarms Table?

**Comment by neuralfraud** [comment]
Get rid of "&filter_status" at the end of your query...you're negating the previous filter 

if all you want is down sensors, then only include "&filter_status=5" and ensure the auto refresh is enabled - the only way the data updates is when the panel/dashboard refreshes.

**Comment by JohnH77** [comment]
thanks, that was the Problem. If i Refresh the Browser Window, there are new updates but the autorefresh in Grafana Dashboard dont work, so you mean to refresh the Browser Windows/tab?

**Comment by neuralfraud** [comment]
Auto refresh works just fine - we have dashboards for sFlow traffic stats that refresh every 30 seconds. How did you configure the "cache timeout" in your PRTG datasource setup? it should be about 1 minute - thats long enough to dedupe unnecessary backend requests and ensure dashboards can refresh frequently enough to be useful.

**Comment by JohnH77** [comment]
The Configuration
![image](https://user-images.githubusercontent.com/30649081/29027621-be633108-7b81-11e7-8e91-2e0d163e8f3d.png)

The Dashboard has three Metrics Graph that works good with grafana autorefresh but the Alarm Table on the same Dashboard dont work, we have to refresh the Browser Tab to refresh the Table. 
An idea what that can be?

**Comment by miquelMariano** [comment]
Hi, how to configure json panel exactely?
If launch the query to api, I returned data, but if configure new panel, JSON is empty

![image](https://user-images.githubusercontent.com/12425938/29528542-b681b2ae-869c-11e7-9e8c-00f2c931bd40.png)

![image](https://user-images.githubusercontent.com/12425938/29528531-ad6f1de6-869c-11e7-858d-70f59970e821.png)

Thanks a lot and good job :)

**Comment by JohnH77** [comment]
@miquelMariano maybe because you need the content for the Grafana. Something like
content=sensors&columns=objid,downtimesince,device,sensor,lastvalue,status,message,priority&filter_status=4

Can you please try the Example with an Dashboard. On my example (Screenshots Above) i have to refresh the Tab in the Browser to see new Json Data. With the auto refresh of Grafana it don't work.

**Comment by miquelMariano** [comment]
Fine, i try with you query and returns me data :)

Thanks a lot!

**Comment by JohnH77** [comment]
@miquelMariano Can you please try the Example with an Dashboard. On my example (Screenshots Above) i have to refresh the Tab in the Browser to see new Json Data. With the auto refresh of Grafana it don't work.

**Comment by JohnH77** [comment]
Can somebody please try the Example with an Dashboard or Table Panel. On my example (Screenshots Above) i have to refresh the Tab in the Browser to see new Json Data. With the auto refresh of Grafana it don't work.
Even with the Template from Github it dont Work

![image](https://user-images.githubusercontent.com/30649081/32887828-7e00560c-cac5-11e7-85d6-a255de9db2d7.png)

**Comment by s035t** [comment]
i have the same problem. Table doesn't refresh, only when i refresh the hole page.

**Comment by JohnH77** [comment]
@neuralfraud i tried the Dashboards with a default.ini config but have the same issue. The Metrics Graph and  Singlestat works fine. Do you have an idea why this not automatically refresh?
Grafana v. 4.6.1

maybe you can sent your Table Example that works?


**my Table Json**

{
  "columns": [
    {
      "text": "status_raw",
      "value": "status_raw"
    },
    {
      "text": "status",
      "value": "status"
    },
    {
      "text": "device",
      "value": "device"
    },
    {
      "text": "sensor",
      "value": "sensor"
    },
    {
      "text": "downtimesince",
      "value": "downtimesince"
    },
    {
      "text": "message_raw",
      "value": "message_raw"
    }
  ],
  "datasource": null,
  "fontSize": "90%",
  "hideTimeOverride": false,
  "id": 8,
  "links": [],
  "minSpan": 1,
  "pageSize": null,
  "repeat": null,
  "scroll": true,
  "showHeader": true,
  "sort": {
    "col": 0,
    "desc": true
  },
  "span": 12,
  "styles": [
    {
      "alias": "#",
      "colorMode": "row",
      "colors": [
        "rgba(50, 172, 45, 0.97)",
        "rgba(132, 107, 3, 0.89)",
        "rgba(245, 54, 54, 0.9)"
      ],
      "dateFormat": "YYYY-MM-DD HH:mm:ss",
      "decimals": 0,
      "pattern": "status_raw",
      "thresholds": [
        "4",
        "5"
      ],
      "type": "number",
      "unit": "short"
    }
  ],
  "targets": [
    {
      "channel": {
        "name": ""
      },
      "device": {
        "name": ""
      },
      "errors": {},
      "functions": [],
      "group": {
        "name": ""
      },
      "hide": false,
      "options": {
        "includeDeviceName": false,
        "includeSensorName": false,
        "mode": {
          "name": "Raw",
          "value": 3
        }
      },
      "raw": {
        "queryString": "content=sensors&columns=objid,downtimesince,device,sensor,lastvalue,status,message,priority&filter_status=5&filter_tags=@tag(-noerror)",
        "uri": "table.json"
      },
      "refId": "A",
      "sensor": {
        "name": ""
      }
    },
    {
      "channel": {
        "name": ""
      },
      "device": {
        "name": ""
      },
      "errors": {},
      "functions": [],
      "group": {
        "name": ""
      },
      "options": {
        "includeDeviceName": false,
        "includeSensorName": false,
        "mode": {
          "name": "Raw",
          "value": 3
        }
      },
      "raw": {
        "queryString": "content=sensors&columns=objid,downtimesince,device,sensor,lastvalue,status,message,priority&filter_status=4&filter_tags=@tag(-noerror)",
        "uri": "table.json"
      },
      "refId": "B",
      "sensor": {
        "name": ""
      }
    }
  ],
  "timeFrom": null,
  "title": "Alarm",
  "transform": "json",
  "type": "table"
}

**Comment by JohnH77** [comment]
i have create a Grafana Playlist and add the Dashboards. 
With Playlist the Table Data are updated automatically. 

I think, i can close here. 
Thanks @neuralfraud for the PRTG-Grafana Plugin

**Comment by istvanSA** [comment]
This is closed because it was "fixed" by using an playlist but this is still an issue which i'm running into also the metrics query from prtg works just fine and refreshed but the table doesnt. I'd rather not use a playlist or  a forcefull refresh on the page because that makes the screen "blink" on the refresh which is annoying if you use it as a bigscreen and you constantly see the page refresh

**Comment by olsonnn** [comment]
Same issue here.

**Comment by ohmar** [comment]
Same issue here. Unfortunate that this was marked as closed.

**Comment by badbart** [comment]
Same issue here.

**Comment by scfigg** [comment]
Same here.

**Comment by BestBackwards** [comment]
Ditto, seems to be the same as #85

**Comment by bashers222** [comment]
Same here

**Comment by Rozz7niner** [comment]
Same here :(

**Comment by BestBackwards** [comment]
@Rozz7niner and everyone else, I'm fairly certain the developer has stopped developing this / caring. So if anyone wants to start developing a new plugin it'd be appreciated.

**Comment by jhavens12** [comment]
Same issue

**Comment by BestBackwards** [comment]
@neuralfraud do you support this plugin anymore? If not please could you delete the repo because it's too buggy for use.

**Comment by My-Random-Thoughts** [comment]
> @neuralfraud do you support this plugin anymore? If not please could you delete the repo because it's too buggy for use.

Unfortunately, there isn't really any alternative (that I have seen)

**Comment by BestBackwards** [comment]
> > @neuralfraud do you support this plugin anymore? If not please could you delete the repo because it's too buggy for use.
> 
> Unfortunately, there isn't really any alternative (that I have seen)

Well, maybe if we put enough pressure on @PRTG we might get something done?

**Comment by sroul** [comment]
Hi @JohnH77 ,

could you please share me the Json file of 
![image](https://user-images.githubusercontent.com/10059576/106860341-4327e300-66ea-11eb-9e0f-a2fe08e9898e.png) 

the dashboard.

i need the same dashboard for my project
 for me data are coming in json format.
How can i visualize them like table format.(as per the image Above)

**Comment by JohnH77** [comment]
> Hi @JohnH77 ,
> 
> could you please share me the Json file of
> ![image](https://user-images.githubusercontent.com/10059576/106860341-4327e300-66ea-11eb-9e0f-a2fe08e9898e.png)
> 
> the dashboard.
> 
> i need the same dashboard for my project
> for me data are coming in json format.
> How can i visualize them like table format.(as per the image Above)

Hi @sroul  

its a Table

![image](https://user-images.githubusercontent.com/30649081/106908163-57c2a600-66ff-11eb-95fe-4dfe6d272e95.png)

String:
content=sensors&columns=objid,downtimesince,device,sensor,lastvalue,status,message,priority&filter_status=5&filter_tags=@tag(-noerror)

String:
content=sensors&columns=objid,downtimesince,device,sensor,lastvalue,status,message,priority&filter_status=4&filter_tags=@tag(-noerror)

















the Same as export: 
my Table Json

{
"columns": [
{
"text": "status_raw",
"value": "status_raw"
},
{
"text": "status",
"value": "status"
},
{
"text": "device",
"value": "device"
},
{
"text": "sensor",
"value": "sensor"
},
{
"text": "downtimesince",
"value": "downtimesince"
},
{
"text": "message_raw",
"value": "message_raw"
}
],
"datasource": null,
"fontSize": "90%",
"hideTimeOverride": false,
"id": 8,
"links": [],
"minSpan": 1,
"pageSize": null,
"repeat": null,
"scroll": true,
"showHeader": true,
"sort": {
"col": 0,
"desc": true
},
"span": 12,
"styles": [
{
"alias": "#",
"colorMode": "row",
"colors": [
"rgba(50, 172, 45, 0.97)",
"rgba(132, 107, 3, 0.89)",
"rgba(245, 54, 54, 0.9)"
],
"dateFormat": "YYYY-MM-DD HH:mm:ss",
"decimals": 0,
"pattern": "status_raw",
"thresholds": [
"4",
"5"
],
"type": "number",
"unit": "short"
}
],
"targets": [
{
"channel": {
"name": ""
},
"device": {
"name": ""
},
"errors": {},
"functions": [],
"group": {
"name": ""
},
"hide": false,
"options": {
"includeDeviceName": false,
"includeSensorName": false,
"mode": {
"name": "Raw",
"value": 3
}
},
"raw": {
"queryString": "content=sensors&columns=objid,downtimesince,device,sensor,lastvalue,status,message,priority&filter_status=5&filter_tags=@tag(-noerror)",
"uri": "table.json"
},
"refId": "A",
"sensor": {
"name": ""
}
},
{
"channel": {
"name": ""
},
"device": {
"name": ""
},
"errors": {},
"functions": [],
"group": {
"name": ""
},
"options": {
"includeDeviceName": false,
"includeSensorName": false,
"mode": {
"name": "Raw",
"value": 3
}
},
"raw": {
"queryString": "content=sensors&columns=objid,downtimesince,device,sensor,lastvalue,status,message,priority&filter_status=4&filter_tags=@tag(-noerror)",
"uri": "table.json"
},
"refId": "B",
"sensor": {
"name": ""
}
}
],
"timeFrom": null,
"title": "Alarm",
"transform": "json",
"type": "table"
}

**Comment by sroul** [comment]
Hi @JohnH77

Thnks for your reply.

But after i wrote the 1st query string i got some json data.

![image](https://user-images.githubusercontent.com/10059576/106922618-3da2bb00-6733-11eb-9ecf-616fbe992073.png)


please let me know how can i get  visualize data like you.

if possible could you please share me the whole json file so that i can import it in the grafana dashboard

**Comment by benisonj** [comment]
![image](https://user-images.githubusercontent.com/96289799/173817172-d7831583-7e8a-4603-ab25-c6637ea02a7a.png)
Try with the transform setting to see in the table.
