### ISSUE TITLE
DataSource Error undefined: undefined

### ISSUE THREAD

**Issue by Photographix** [neuralfraud/grafana-prtg#54]
Hello I did everything like in the wiki. I have Grafana 4.4.3 x64 in use. The registry entry has been set. I set the Grafana Port to 8080. Grafana runs locally on the PRTG server (Windows 2012 R2 x64). PRTG Version 17.3.33.2654

As a user I first used a dedicated one, then one with admin rights, then my own.
Unfortunately, I always get **undefined: undefined** as an error. Picture attached. Where might be my mistake?

![2017-09-01 13_43_51-prtg](https://user-images.githubusercontent.com/16647382/29968404-cec945de-8f1b-11e7-9141-6ac934759dfb.png)

**Comment by stephanlinke** [comment]
Does setting **Access** to _direct_ instead of _proxy_ work?

**Comment by Photographix** [comment]
No 
![2017-09-01 15_02_01-prtg1](https://user-images.githubusercontent.com/16647382/29970892-b20bc5b0-8f26-11e7-8ea8-6b2941029d77.png)

**Comment by Photographix** [comment]
No

![2017-09-01 15_02_01-prtg1](https://user-images.githubusercontent.com/16647382/29970943-d2181e3a-8f26-11e7-8fd2-82791ad6bfdc.png)

**Comment by Photographix** [comment]
PRTG is connected via HTTPS

**Comment by Photographix** [comment]
![2017-09-01 15_08_05-prtg2](https://user-images.githubusercontent.com/16647382/29971117-74b86d7a-8f27-11e7-9a98-ac092fabd637.png)

**Comment by JohnH77** [comment]
@Photographix: have you try to restart the PRTG Server after changing the Registry Value?

I have a readonly api User, works fine

![image](https://user-images.githubusercontent.com/30649081/29971254-e9e8854e-8f27-11e7-9983-c791402e2694.png)

**Comment by Photographix** [comment]
Okay, I'm sorry the mistake was mine. I still needed the passhash and always thought of password. That was exactly the mistake. 

maybe you should write that a bit "clearer" in the instructions and how to find the passhash

Everything works. thank you
