### ISSUE TITLE
How to get table/chart of down sensors?

### ISSUE THREAD

**Issue by tocheeba** [neuralfraud/grafana-prtg#57]
I can't seem to figure out how to create a table of down/warning sensors, similar to what's on the wiki page. Can anyone share info on how they have it setup? (also, stupid question - any way to trigger an audible alert when there is a downed sensor?)

Thanks!

**Comment by JohnH77** [comment]
Maybe my Ticket #51 can help you.  
You need two metrics, one for Warning and one for Critical Alarm. 
![image](https://user-images.githubusercontent.com/30649081/30097729-44eb89c2-92df-11e7-84e8-e8fdf0f8793f.png)


Then you can change The Colors for the output. 
![image](https://user-images.githubusercontent.com/30649081/30097747-6559824a-92df-11e7-8782-108e7ef8894d.png)

I dont find a possibility to trigger an audible alert but there is an  feature request
https://github.com/grafana/grafana/issues/6778

**Comment by tocheeba** [comment]
Thanks for your help!
