### ISSUE TITLE
PRTG Dashboards

### ISSUE THREAD

**Issue by FlorianFL** [neuralfraud/grafana-prtg#59]
Hi Jason, as far as i have seen you had some pretty dashboards in your example. Could you maybe share them? Im new to grafana so it might be a great help to have some sample dashboard in order to customize it for the own purpose. 

Thank you for all your work

**Comment by xxKryptonite** [comment]
I think you are looking for what I asked for earlier located [HERE](https://github.com/neuralfraud/grafana-prtg/issues/50)

**Comment by FlorianFL** [comment]
Hi Kryptonite first of all thank you very much for your reply it was pretty much what i was looking for. The only issue still is, that i can't handle the colour on different states for example if a sensor went down it should change into red within the table or if a sensor is up it should change into green.  As shown on this picture https://camo.githubusercontent.com/a89371c6c0ef8e99c8e6a99b26d128feea1a0763/68747470733a2f2f6e657572616c66726175642e6769746875622e696f2f67726166616e612e706e67 . I guess reason for that is because i need a number value instead of a string value within this table same as shown in the picture (# column). Regarding this i was browsing through a little while until i found that article https://github.com/grafana/grafana/pull/9455 i believe the next update of grafana will include a solution to even change the string value colour in tables but until that i do not have a solution so far.

**Comment by neuralfraud** [comment]
Query:

content=sensors&columns=device,sensor,status,status,message&filter_status=4&filter_status=5

Columns:

Data

Table Transform

Columns
 status_raw
 status
 device
 sensor
 message_raw

finally, the color transform:

![image](https://user-images.githubusercontent.com/8482103/32121395-797991f2-bb2a-11e7-8fe7-c27d7f814ae7.png)
