### ISSUE TITLE
Get Error Connection failed by Edit data source

### ISSUE THREAD

**Issue by heydemar** [neuralfraud/grafana-prtg#6]
Hello, i have a Problem so add a data source.

i get error:

Connection failed
Could not connect to /api/datasources/proxy/2/status.json?username=mheyder&password=****+&undefined

If i switch the Access to direct i get:

Unknown error
error.config is undefined

Thanks for help!!

**Comment by neuralfraud** [comment]
What version of Grafana are you using?

**Comment by heydemar** [comment]
Good Morning, 

Grafana 2.6.0
PRTG 15.4.21.5482

**Comment by neuralfraud** [comment]
The only thing i can think of with the limited information you've provided is that the url to the PRTG API may be wrong or the plugin installed in the wrong folder - the config has static references so it must be in a folder called "PRTG". 

screenshot?

**Comment by cakered** [comment]
I ran in to this error, and it was because I hadn't specified /api on the end of the URL

**Comment by neuralfraud** [comment]
@cakered - good find. I have updated the Wiki page to clarify that the URL should include "/api".

Thank you.
