### ISSUE TITLE
Error: a(...).finally us bit a function

### ISSUE THREAD

**Issue by Deph0** [neuralfraud/grafana-prtg#61]
Hi, I am getting this when I try to add PRTG as a datasource, when saving and testing, this error comes up.
I installed the plugin from grafanas webbpage using the cli.

Error log:
![image](https://user-images.githubusercontent.com/3504896/30585789-393f984e-9d2e-11e7-9334-42509907b329.png)

Config (stuck on "Testing..."):
![image](https://user-images.githubusercontent.com/3504896/30585982-c845f20e-9d2e-11e7-8964-5c961f17bdde.png)

**Comment by neuralfraud** [comment]
Use version 4.4.1 or 4.6.0
