### ISSUE TITLE
IPFIX Sensor - All Channel Data Identical

### ISSUE THREAD

**Issue by AbsoZed** [neuralfraud/grafana-prtg#66]
Set up a custom IPFIX Sensor in PRTG that polls my firewall device.

However, all the data in PRTG appears correct, but when polled via the API, all the data for each channel appears identical. Not sure where to begin troubleshooting - see attached screenshot.

Other SNMP or Factory Sensors appear normal and ingress/egress traffic is correctly reported elsewhere.

![capture](https://user-images.githubusercontent.com/17788335/32583922-72880474-c4bb-11e7-9f5a-554ae7d1cd9e.PNG)

**Comment by neuralfraud** [comment]
In the graph editor screen, If using chrome, open dev tools and then press F5 to refresh. Go to the network tab and look for the request for "histdata.xml". Paste a sample of that which shows at least a few consecutive time periods.

**Comment by AbsoZed** [comment]
See below samples of HistoricData.xml

` <item>
    <datetime>11/8/2017 5:00:00 PM - 6:00:00 PM</datetime>
    <datetime_raw>43048.0000000000</datetime_raw>
    <value channel="Total (volume)" channelid="-1">3,181 KByte</value>
    <value_raw channel="Total (volume)" channelid="-1">3257005.0000</value_raw>
    <value channel="Total (speed)" channelid="-1">7.24 kbit/s</value>
    <value_raw channel="Total (speed)" channelid="-1">904.7714</value_raw>
    <value channel="Email (volume)" channelid="2">43 KByte</value>
    <value_raw channel="Email (volume)" channelid="2">44376.0000</value_raw>
    <value channel="Email (speed)" channelid="2">0.10 kbit/s</value>
    <value_raw channel="Email (speed)" channelid="2">12.3273</value_raw>
    <value channel="Chat (volume)" channelid="3">0 KByte</value>
    <value_raw channel="Chat (volume)" channelid="3">0.0000</value_raw>
    <value channel="Chat (speed)" channelid="3">0 kbit/s</value>
    <value_raw channel="Chat (speed)" channelid="3">0.0000</value_raw>
    <value channel="DHCP (volume)" channelid="5">0 KByte</value>
    <value_raw channel="DHCP (volume)" channelid="5">0.0000</value_raw>
    <value channel="DHCP (speed)" channelid="5">0 kbit/s</value>
    <value_raw channel="DHCP (speed)" channelid="5">0.0000</value_raw>
    <value channel="NetBIOS (volume)" channelid="6">0.21 KByte</value>
    <value_raw channel="NetBIOS (volume)" channelid="6">212.0000</value_raw>
    <value channel="NetBIOS (speed)" channelid="6">&lt; 0.01 kbit/s</value>
    <value_raw channel="NetBIOS (speed)" channelid="6">0.0589</value_raw>
    <value channel="HTTP (volume)" channelid="7">371 KByte</value>
    <value_raw channel="HTTP (volume)" channelid="7">380395.0000</value_raw>
    <value channel="HTTP (speed)" channelid="7">0.85 kbit/s</value>
    <value_raw channel="HTTP (speed)" channelid="7">105.6709</value_raw>
    <value channel="HTTPS (volume)" channelid="8">1,251 KByte</value>
    <value_raw channel="HTTPS (volume)" channelid="8">1281284.0000</value_raw>
    <value channel="HTTPS (speed)" channelid="8">2.85 kbit/s</value>
    <value_raw channel="HTTPS (speed)" channelid="8">355.9310</value_raw>
    <value channel="RDP (volume)" channelid="15">1,309 KByte</value>
    <value_raw channel="RDP (volume)" channelid="15">1340118.0000</value_raw>
    <value channel="RDP (speed)" channelid="15">2.98 kbit/s</value>
    <value_raw channel="RDP (speed)" channelid="15">372.2746</value_raw>
    <value channel="SSH (volume)" channelid="16">0.18 KByte</value>
    <value_raw channel="SSH (volume)" channelid="16">188.0000</value_raw>
    <value channel="SSH (speed)" channelid="16">&lt; 0.01 kbit/s</value>
    <value_raw channel="SSH (speed)" channelid="16">0.0522</value_raw>
    <value channel="DNS (volume)" channelid="19">163 KByte</value>
    <value_raw channel="DNS (volume)" channelid="19">167113.0000</value_raw>
    <value channel="DNS (speed)" channelid="19">0.37 kbit/s</value>
    <value_raw channel="DNS (speed)" channelid="19">46.4227</value_raw>
    <value channel="ICMP (volume)" channelid="21">41 KByte</value>
    <value_raw channel="ICMP (volume)" channelid="21">42395.0000</value_raw>
    <value channel="ICMP (speed)" channelid="21">0.09 kbit/s</value>
    <value_raw channel="ICMP (speed)" channelid="21">11.7770</value_raw>
    <value channel="SNMP (volume)" channelid="22">0.83 KByte</value>
    <value_raw channel="SNMP (volume)" channelid="22">851.0000</value_raw>
    <value channel="SNMP (speed)" channelid="22">&lt; 0.01 kbit/s</value>
    <value_raw channel="SNMP (speed)" channelid="22">0.2364</value_raw>
    <value channel="Hyper-V Replication (volume)" channelid="24">0.07 KByte</value>
    <value_raw channel="Hyper-V Replication (volume)" channelid="24">73.0000</value_raw>
    <value channel="Hyper-V Replication (speed)" channelid="24">&lt; 0.01 kbit/s</value>
    <value_raw channel="Hyper-V Replication (speed)" channelid="24">0.0203</value_raw>
    <coverage>100 %</coverage>
    <coverage_raw>0000009999</coverage_raw>
   </item>
   <item>
    <datetime>11/8/2017 6:00:00 PM - 7:00:00 PM</datetime>
    <datetime_raw>43048.0416666667</datetime_raw>
    <value channel="Total (volume)" channelid="-1">1,761 KByte</value>
    <value_raw channel="Total (volume)" channelid="-1">1803209.0000</value_raw>
    <value channel="Total (speed)" channelid="-1">4 kbit/s</value>
    <value_raw channel="Total (speed)" channelid="-1">500.9178</value_raw>
    <value channel="Email (volume)" channelid="2">31 KByte</value>
    <value_raw channel="Email (volume)" channelid="2">31466.0000</value_raw>
    <value channel="Email (speed)" channelid="2">0.07 kbit/s</value>
    <value_raw channel="Email (speed)" channelid="2">8.7410</value_raw>
    <value channel="Chat (volume)" channelid="3">0.02 KByte</value>
    <value_raw channel="Chat (volume)" channelid="3">20.0000</value_raw>
    <value channel="Chat (speed)" channelid="3">&lt; 0.01 kbit/s</value>
    <value_raw channel="Chat (speed)" channelid="3">0.0056</value_raw>
    <value channel="DHCP (volume)" channelid="5">0 KByte</value>
    <value_raw channel="DHCP (volume)" channelid="5">0.0000</value_raw>
    <value channel="DHCP (speed)" channelid="5">0 kbit/s</value>
    <value_raw channel="DHCP (speed)" channelid="5">0.0000</value_raw>
    <value channel="NetBIOS (volume)" channelid="6">0.11 KByte</value>
    <value_raw channel="NetBIOS (volume)" channelid="6">112.0000</value_raw>
    <value channel="NetBIOS (speed)" channelid="6">&lt; 0.01 kbit/s</value>
    <value_raw channel="NetBIOS (speed)" channelid="6">0.0311</value_raw>
    <value channel="HTTP (volume)" channelid="7">213 KByte</value>
    <value_raw channel="HTTP (volume)" channelid="7">217839.0000</value_raw>
    <value channel="HTTP (speed)" channelid="7">0.48 kbit/s</value>
    <value_raw channel="HTTP (speed)" channelid="7">60.5140</value_raw>
    <value channel="HTTPS (volume)" channelid="8">857 KByte</value>
    <value_raw channel="HTTPS (volume)" channelid="8">877354.0000</value_raw>
    <value channel="HTTPS (speed)" channelid="8">1.95 kbit/s</value>
    <value_raw channel="HTTPS (speed)" channelid="8">243.7223</value_raw>
    <value channel="RDP (volume)" channelid="15">503 KByte</value>
    <value_raw channel="RDP (volume)" channelid="15">514909.0000</value_raw>
    <value channel="RDP (speed)" channelid="15">1.14 kbit/s</value>
    <value_raw channel="RDP (speed)" channelid="15">143.0378</value_raw>
    <value channel="SSH (volume)" channelid="16">0.27 KByte</value>
    <value_raw channel="SSH (volume)" channelid="16">277.0000</value_raw>
    <value channel="SSH (speed)" channelid="16">&lt; 0.01 kbit/s</value>
    <value_raw channel="SSH (speed)" channelid="16">0.0769</value_raw>
    <value channel="DNS (volume)" channelid="19">113 KByte</value>
    <value_raw channel="DNS (volume)" channelid="19">115596.0000</value_raw>
    <value channel="DNS (speed)" channelid="19">0.26 kbit/s</value>
    <value_raw channel="DNS (speed)" channelid="19">32.1117</value_raw>
    <value channel="ICMP (volume)" channelid="21">44 KByte</value>
    <value_raw channel="ICMP (volume)" channelid="21">44865.0000</value_raw>
    <value channel="ICMP (speed)" channelid="21">0.10 kbit/s</value>
    <value_raw channel="ICMP (speed)" channelid="21">12.4632</value_raw>
    <value channel="SNMP (volume)" channelid="22">0.66 KByte</value>
    <value_raw channel="SNMP (volume)" channelid="22">679.0000</value_raw>
    <value channel="SNMP (speed)" channelid="22">&lt; 0.01 kbit/s</value>
    <value_raw channel="SNMP (speed)" channelid="22">0.1886</value_raw>
    <value channel="Hyper-V Replication (volume)" channelid="24">0.09 KByte</value>
    <value_raw channel="Hyper-V Replication (volume)" channelid="24">92.0000</value_raw>
    <value channel="Hyper-V Replication (speed)" channelid="24">&lt; 0.01 kbit/s</value>
    <value_raw channel="Hyper-V Replication (speed)" channelid="24">0.0256</value_raw>
    <coverage>100 %</coverage>
    <coverage_raw>0000009999</coverage_raw>
   </item>`

**Comment by AbsoZed** [comment]
Looks like to me that the graph is returning the total for all channels for some reason - see 

> value_raw channel="Total (volume)" channelid="-1">3257005.0000</value_raw>

Not sure why this would be. Also, my units in the graph are wrong - should be bits/sec, I believe. Not that it's relevant to the issue at hand.

**Comment by neuralfraud** [comment]
What does the query look like? The data looks fine and I've used sflow
sensors with no issue.

Also what plugin version are you using, and what version of grafana?

On Nov 8, 2017 9:19 PM, "AbsoZed" <notifications@github.com> wrote:

Looks like to me that the graph is returning the total for all channels for
some reason - see

value_raw channel="Total (volume)" channelid="-1">3257005.0000</value_raw>

Not sure why this would be. Also, my units in the graph are wrong - should
be bits/sec, I believe. Not that it's relevant to the issue at hand.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/neuralfraud/grafana-prtg/issues/66#issuecomment-343026616>,
or mute the thread

**Comment by AbsoZed** [comment]
Where can I get that information for you? I have one of my devs assisting me currently in trying to figure this out, but I can't seem to get the 'Query View' pane to load on my end.

**Comment by neuralfraud** [comment]
Weird, just open the dashboard, hover over the graph that wont work right and hit “E” to edit, and you’ll see the query editor pane

 

Unless that’s what isn’t working!

 

The plugin version can be seen in the grafana plugins menu, it should show you a version, also the about grafana view.

 

Thanks

**Comment by AbsoZed** [comment]
I did manage to solve the problem - by excluding total from tables in PRTG.  However, find a snip of the query attached. (Or, at least, what would load.)
![2017-11-10 07_53_01-grafana - sonicwall dashboard](https://user-images.githubusercontent.com/17788335/32661348-381f76c8-c5ec-11e7-8c72-a3b05670706b.png)

**Comment by neuralfraud** [comment]
That doesn't look right. 

for your query, if you want everything but total, you should have a single metric query - use a Regular Expression like /Total/ and then click "Invert Channel Filter" 

You also have filter property "Status" with no filter string, may cause a problem, not sure. 

Try deleting those queries and save the dashboard, then go back and edit it again.
