### ISSUE TITLE
Grafan to PRTG not working Red triangle ! Nothing else

### ISSUE THREAD

**Issue by ccie9360** [neuralfraud/grafana-prtg#67]
Loving the work you did here and am trying to follow in your steps, so thank you. I followed all installation instructions here is an overview.

-prtg and grafana on same win2012 server
-both current with latest stable
-created new user 'apiuser'
-placed apiuser, primary group is prtg admin
-yes i am using the password HASH from prtg in the edit data source screen
-I have restarted grafan and the server its on

Nothing i have done, including try a ton of options has made a difference. I am learning to hate this red mark in grafan... It says nothing.

I can create a query with this user and the password HASH and put it in a browser, it works and I can get a table. I can login in to prtg with this user.

Any thoughts?

Ps I posted in the grafan forums, no replies after several days so posting here. Oh and I even tried to contact them to pay to get some help, no reply there either.

**Comment by neuralfraud** [comment]
Are you using "proxy" or "direct" mode?

![image](https://user-images.githubusercontent.com/8482103/32702262-38bb13ea-c7b2-11e7-8331-d460ed936b23.png)

**Comment by ccie9360** [comment]
Correct using proxy and nothing else, following the screen shot in the installation instructions. There are two differences in my screen and this on here. 
1 - I am using https not http, i did try it with http, no change still fails
2 - I am using the actual ip address not the loopback, though I did try the loopback and no change still fails.

Tom

**Comment by mberniz** [comment]
Check Skip TLS verification

**Comment by ccie9360** [comment]
Yes that was one of the options I tried while troubleshooting when I 
attempting to connect vis http, it made no difference still the 
uninformative red exclamation point, stating it failed.

I did try it again this Morning just to be sure, no change in behavior.

**Comment by neuralfraud** [comment]
Ok bud, Fire up chrome, go to the datasource configuration page, and then:

- hit the F12 key to open the chrome developer tools window. 
- In the developer tools window, click over to the network tab. 
- go back to the datasource configuration page and hit the "Save & Test" button. 
- Go back to the developer tools window and send look for a transaction named "Status.json?username=...." and "getstatus.htm". Select the first transaction you see. The response ought to be displayed and it should be a JSON object with a bunch of PRTG information. 
- Send a screenshot or copy/paste of those responses 

Also which version of grafana have you installed? I've tested with 4.4 and 4.6.0 - version 4.5 was known to have a bug that essentially broke everything and was fixed in version 4.6.0

**Comment by jott0204** [comment]
If you are using a custom port number in PRTG, then you will need to include that.
 ie. 
   - https://127.0.0.1:9090/api
   - https://127.0.0.1:8282/api

**Comment by ccie9360** [comment]
Good Evening Gentlemen, Thank you both for your help. Today while troubleshooting a completely unrelated issue with PRTG tech support they took a peek at the Grafana configuration. Apparently the PRTG Engineer has had the same issue as I did and is familiar with Grafana. Long story short while I am not custom port in PRTG I did have to "force" port 443 in addition to having it be a https URL, please see the picture for the final configuration that is working.

Now I got the impression this was needed because prtg and grafana are on the same server. 
<img width="647" alt="screen shot 2017-11-13 at 7 18 38 pm" src="https://user-images.githubusercontent.com/33604738/32761369-cfd73844-c8a7-11e7-9805-3b44e57df9a3.png">

**Comment by neuralfraud** [comment]
I'm glad that Paessler was able to help you. They've been very kind and helpful to me as a developer and customer! 

You should avoid direct access mode, as that forces the browser to initiate the connection, instead of the Grafana server itself, which is more reliable and provides a security barrier of sorts. 

What'd you configure in the registry for the AccessControlAllowOrginHTTPHeader key?

**Comment by ccie9360** [comment]
yes they are and its one of the reasons I dumped solarwinds and went 
with them, so much easier to work with.

I set the registry to be exactly what was shown in the install 
instructions, a asterisk if I recall. Now since this is a 2012 server it 
didn't exist so I created it.

I do wish proxy would work as your reasons are sound and I agree with them.

Tom

**Comment by jjfaulk1967** [comment]
Neuralfraud, I am still having problems after all the comments here. I perform a save & test but usually never get a result or a failed result. Only once did I briefly see a success. Could you take a look at my debug from Chrome?

thanks

General:
Request URL:http://10.154.66.50:3000/api/datasources/proxy/1/status.json?username=APIUSER&passhash=4004094053&undefined
Request Method:GET
Status Code:302 Found
Remote Address:10.154.66.50:3000
Referrer Policy:no-referrer-when-downgrade

Response Headers:
Access-Control-Allow-Origin:*
Cache-Control:no-cache
Cache-Control:no-cache
Content-Length:0
Content-Type:text/html; charset=ISO-8859-1
Date:Thu, 30 Nov 2017 14:53:10 GMT
Expires:0
Expires:-1
Location:https://10.154.66.61/api/status.json?username=APIUSER&passhash=4004094053&undefined
Pragma:no-cache
Server:PRTG/17.4.35.3326
X-Content-Type-Options:nosniff
X-Xss-Protection:1; mode=block

Request Headers:
Accept:application/json, text/plain, */*
Accept-Encoding:gzip, deflate
Accept-Language:en-US,en;q=0.9
Connection:keep-alive
Cookie:grafana_user=admin; grafana_remember=28653add0d6a0df126092d43bcb5b30dcc0236e8aef52a510a78403dcda5aefe73; grafana_sess=541c419e23788e88; OCTOPUS174353326=ezBGQTQ0QzRFLUZFM0ItNDlFNy05NUFBLTk5RTJEMjAwREQ4N30%3D
Host:10.154.66.50:3000
Referer:http://10.154.66.50:3000/datasources/edit/1
User-Agent:Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36
X-Grafana-NoCache:true
X-Grafana-Org-Id:1

Query String Parameters:
username:APIUSER
passhash:4004094053
undefined:

**Comment by jjfaulk1967** [comment]
Update. I am now getting the add datasource save & test to work.  But when using '*' in the group field I get this response.

 xhrStatus:"complete"
request:Object
method:"GET"
url:"api/datasources/proxy/1/table.json?username=XXXX&passhash=[object Object]&content=devices&count=9999&columns=objid,device,group,probe,tags,active,status,message,priority"
response:"<HTML><BODY><B>Unauthorized</B></BODY></HTML>"

I have tripled checked to user account (default admin account) on PRTG and it has permission for all hosts and sensors.  I have used the hashpass from PRTG when configuring the datasource.

**Comment by neuralfraud** [comment]
Just hit F5 /refresh.

 

You save the datasource, you get the green success box. You go create a graph or load a dashboard and you get request errors. 

 

Hitting F5 / refresh appears to resolve that initial glitch – I haven’t gotten to identifying the cause yet. 

 

J

**Comment by jjfaulk1967** [comment]
Thanks Neuralfraud. Making progress. I am now seeing entries in the field.  Missing quite a few groups, hosts, and sensors. And another oddity, I have some hosts listed in the group field. 

Thanks ALOT for your help so far.

John

**Comment by alxgrb** [comment]
Hi,
thx fo the great work!!!
but i have the same problem with red triangle, please look at the screenshot.
my Server has;
WindowsServer 2012R2
PRTG Ver. 18.1.36.37.33
Grafana 4.6.3
![capture-grafana-error](https://user-images.githubusercontent.com/26403641/35926718-168e9542-0c29-11e8-8ac4-995c91499aec.PNG)

any Idea?

thx,
Alex

**Comment by jott0204** [comment]
put this in your URL


   - https://127.0.0.1:8085/api/getstatus.htm?id=0

*OR JUST*


   - https://127.0.0.1:8085/api


I'm guessing that you have a specific port number in PRTG and that is what
you need to use. Let me know if that works for you

*James Ott, Jr.*
*IT Administrator **| Network Engineer*

CompTIA Linux+
<http://t.sidekickopen05.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XYg7gsh4lVQZpyx8pTkCFW5vMqt056dGr7f6ZlqFx02?t=https%3A%2F%2Fdrive.google.com%2Fopen%3Fid%3D0B0Nd3DEOXzcjTUk3WjUxTFVaVnM&si=6377182977064960&pi=c5c71688-0594-46ed-a0bb-5ad2887eea78>
/ LPIC-1
<http://t.sidekickopen05.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XYg7gsh4lVQZpyx8pTkCFW5vMqt056dGr7f6ZlqFx02?t=https%3A%2F%2Fdrive.google.com%2Fopen%3Fid%3D0B0Nd3DEOXzcjMHUwVU5vSFJ4amM&si=6377182977064960&pi=c5c71688-0594-46ed-a0bb-5ad2887eea78>
/ SUSE-CLA
<http://t.sidekickopen05.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XYg7gsh4lVQZpyx8pTkCFW5vMqt056dGr7f6ZlqFx02?t=https%3A%2F%2Fdrive.google.com%2Fopen%3Fid%3D0B0Nd3DEOXzcjWGVWaXFlU1AyQzg&si=6377182977064960&pi=c5c71688-0594-46ed-a0bb-5ad2887eea78>

------------------------------


[image: Email Signature Logo]
<http://t.sidekickopen05.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XYg7gsh4lVQZpyx8pTkCFW5vMqt056dGr7f6ZlqFx02?t=http%3A%2F%2Fwww.federalradio.net%2F&si=6377182977064960&pi=c5c71688-0594-46ed-a0bb-5ad2887eea78>


*Pegasus Radio Corp / FEDERAL RADIO*
1202 Technology Park, Suite C
Aberdeen, Maryland 21001

(P) 410.273.7611 <(410)%20273-7611> | (F) 410.273.7605 <(410)%20273-7605>
(M) 443.617.0034 <(443)%20617-0034> | (CS) 800.718.4111 <(800)%20718-4111>

PHONE EXT: 107

**Comment by alxgrb** [comment]
Thx, but it doesn't work....
i have tried with your tips
![capture-grafana-error1800208](https://user-images.githubusercontent.com/26403641/35970169-acade6b8-0cc9-11e8-892f-9fa265117322.PNG)

a standard ports
![capture-grafana-error1800208-prtg-adm](https://user-images.githubusercontent.com/26403641/35970226-dfe34dde-0cc9-11e8-99b4-d96363587fbb.PNG)

webserver config
![capture-grafana-error1800208-prtg-webserver](https://user-images.githubusercontent.com/26403641/35970406-8539d2da-0cca-11e8-9a0b-6b06236735bf.PNG)

**Comment by JohnH77** [comment]
@alxgrb you have to take passhash, not the password. With passhash ist should work

**Comment by alxgrb** [comment]
It's won't work with a passhash....
but look at screenshots
![capture-grafana-w passhash1](https://user-images.githubusercontent.com/26403641/35978355-c979d6fa-0ce5-11e8-9249-0124b0e55e62.PNG)
![capture-grafana-w passhash2](https://user-images.githubusercontent.com/26403641/35978360-cb9c5534-0ce5-11e8-8091-3f370b22b4d4.PNG)
![capture-grafana-w passhash3](https://user-images.githubusercontent.com/26403641/35978364-cda2702a-0ce5-11e8-912b-925d67f7a0ef.PNG)

**Here is without starting grafana**
![capture-prtgwebsite1](https://user-images.githubusercontent.com/26403641/35978369-cfa6487e-0ce5-11e8-89e5-4ca0e8d281aa.PNG)
![capture-prtgwebsite2](https://user-images.githubusercontent.com/26403641/35978372-d163720e-0ce5-11e8-9732-0e422ce97484.PNG)

**Comment by JohnH77** [comment]
@alxgrb You use the standard SSL 443 Port or 8085?
Can you try to open the PRTG Api, does ist works?

![image](https://user-images.githubusercontent.com/30649081/35979268-30d20f50-0ce8-11e8-82c8-ceec08448ae6.png)

**Comment by JohnH77** [comment]
maybe it cant be used with Port 8085 because:
![image](https://user-images.githubusercontent.com/30649081/35979602-06e3c160-0ce9-11e8-84fa-2fee5f61ad64.png)

**Comment by alxgrb** [comment]
Hi,

i've changed the port to 8087, the result =>
API works,without problems
![capture-grafana-prtg-api](https://user-images.githubusercontent.com/26403641/35984205-3a1658c6-0cf4-11e8-923b-71314c68bd25.PNG)
![capture-grafana-prtg-port-changed1](https://user-images.githubusercontent.com/26403641/35984208-3c011dd8-0cf4-11e8-8ae7-aecfe5bf16b9.PNG)
![capture-grafana-prtg-port-changed1b](https://user-images.githubusercontent.com/26403641/35984215-41f9bbd2-0cf4-11e8-8533-aa0991c7cb7a.PNG)

**Comment by JohnH77** [comment]
@alxgrb  habe you tryed the Options like  @ccie9360  write above and use the Port 443?
Set the Registry key? https://github.com/neuralfraud/grafana-prtg/wiki/Installation

**Comment by alxgrb** [comment]
It's work!!!
I found the error, it was in the registry. I have set 1 must be *
![capture-grafana-registry](https://user-images.githubusercontent.com/26403641/36033270-d6c13472-0db0-11e8-99b6-5a3c180a5dc3.PNG)

![capture-grafana-ok](https://user-images.githubusercontent.com/26403641/36033273-d94726ca-0db0-11e8-95dc-3cd3409261e0.PNG)

Many Thx for All !!!!

**Comment by alxgrb** [comment]
Hallo again!

This message ERR_CERT_COMMON_NAME_INVALID came after PRTG update to 18.1.37.13946 
& nothing was changed....

![grafik](https://user-images.githubusercontent.com/26403641/36902487-e871a136-1e2a-11e8-9804-da58a59a22df.png)

**Comment by alxgrb** [comment]
Hi to all,

please update the PRTG to version 18.1.38.11934.
![grafik](https://user-images.githubusercontent.com/26403641/37199501-268089a4-2382-11e8-993a-fd57fc421c6e.png)

and read this security issue => https://www.paessler.com/about-prtg-17-4-35-through-18-1-37

after update & restart, works all fine
