### ISSUE TITLE
Trouble with newest version of PRTG

### ISSUE THREAD

**Issue by xxKryptonite** [neuralfraud/grafana-prtg#70]
Anyone having trouble with the newest version of PRTG? After updating to 17.4.35, my dashboards are not getting any data.  It appears that the API is still working because I can query different metrics but no data is being populated.

**Comment by neuralfraud** [comment]
I tested on my PC – which is what I use for development. I’m using the Free license and PRTG and Grafana both run from 127.0.0.1

 

The current release seems to work just fine. 

 

*	Make sure your time range is not too short, too recent
*	Try the refresh button in the browser 

 

If that doesn’t work then I need to know more about your use case. Topology, etc.

**Comment by xxKryptonite** [comment]
I think it is related to the time range as you suggested.  The way it is working is really odd.  For any of the "Last X hours/mins" options I get N/A except for "Last 24 Hours" which gives NaN.  But if I choose any larger time frame, I start getting data.  I was using "Last 1 Hour" prior to the update and it was working.  I am thinking that after the update, there was a gap in data while the update was being applied.  So when PRTG started running again, my dashboard never recovered due to the gap in data.

Is the issue not having a full data-set?  Maybe there was a change in the way PRTG handles null/empty?

I have tried multiple grafana installations and get the same results.

**Comment by xxKryptonite** [comment]
This what one of my dashboards looks like when I set the time frame to one week:

![image](https://user-images.githubusercontent.com/21250166/33682819-9f00359e-da7d-11e7-8b61-7dc3d1141cf7.png)

You can see that it is working fine until I did the PRTG update at which point I get NaN.  Any idea what might cause this?

**Comment by xxKryptonite** [comment]
Issue resolved.

**Comment by lalafrosch** [comment]
I also have trouble with PRTG Version 17.4.35.3441. This is the first time installing Grafana and in the initial datasource setup I keep getting error. The grafana log says:

**Comment by xxKryptonite** [comment]
The error you have is different than the error I had.  I also get that error when using the newest version of Grafana.  Use version 4.4.1 and  it should work as expected.  I am assuming there are some changes in the newer releases of Grafana that break the plugin. I think @neuralfraud will need to update it to be compatible with the newest version, but for now, you can use the older one.
