### ISSUE TITLE
Singlestat coloring and value mappings not working

### ISSUE THREAD

**Issue by ohmar** [neuralfraud/grafana-prtg#74]
Hello,

I'm trying to create a singlestat panel that updates the background color according to the value returned by status_raw. (3 = green, 4 = yellow, 5 = red). Changing this under "options" doesn't seem to do anything.

![image](https://user-images.githubusercontent.com/2738000/34808380-65f86cda-f643-11e7-8439-93332e056804.png)

Value Mappings also don't work.

![image](https://user-images.githubusercontent.com/2738000/34808395-8106a406-f643-11e7-9e9c-3fca82627e66.png)

Anyone else seeing the same issue?

**Comment by JohnH77** [comment]
i have the same issue, the "value to text" dont work. 
"range to text" works if i set From 0 
From 1 or more dont work. 
And i have to refresh the Grafana Tab to show the text. 

Grafana v4.6.2 (commit: 8db5f087e)

![grafik](https://user-images.githubusercontent.com/30649081/35384651-4b6b7770-01c6-11e8-9cb2-e4af5d83f0e0.png)
![grafik](https://user-images.githubusercontent.com/30649081/35384703-7e9518e0-01c6-11e8-81e2-bc590f17d4cb.png)

**Comment by olsonnn** [comment]
Same issue here.

**Comment by tomwel1** [comment]
Same issue here. The singlestat item shows the correct status but doesnt change the tile from green to red if in error/down state.

**Comment by Steve8000** [comment]
Reporting the same issues with Value mappings & Colours not changing.
PRTG: 18.1.36.3728+
Grafana: 4.6.3

**Comment by joaogvmoura** [comment]
Same issue here...

Grafana: 5.0.0
PRTG: 18.1.38.11934+

**Comment by Catt00** [comment]
Have the same issue as well
 Grafana v4.6.3 
PRTG; 18.1.36.3728+

**Comment by mhutchison89** [comment]
+1   : )

PRTG: 17.3.33.2686+ 
Grafana: v5.1 and v5.0

**Comment by dyanca** [comment]
I had this issue when we were sending the numeric value inside quotes, forcing the number to be a string.  Once we changed that to come in just as a number, our value mapping worked as expected.

**Comment by Yakelixir** [comment]
Currently using grafana-prtg and I'm seeing the same issue with single stat panels.

**Comment by olsonnn** [comment]
As we have zero response from the dev. you have to fix it yourself probably

**Comment by CWempe** [comment]
According to https://github.com/NatelEnergy/grafana-discrete-panel/issues/58#issuecomment-391294605 this has been fixed in Grafana itself.

**Comment by bchris999** [comment]
Same issue here. Grafana 5.4.3.

**Comment by chaispaquichui** [comment]
Same issue

**Comment by miroslavpetrov** [comment]
![grafana](https://user-images.githubusercontent.com/25277610/58531796-3a300000-81ec-11e9-8e77-0620464a8fb9.PNG)

Have you selected "name" on stat?

**Comment by neuralfraud** [comment]
Not a datasource plugin issue.
