### ISSUE TITLE
values doesnt load on grafana

### ISSUE THREAD

**Issue by theburakcinar** [neuralfraud/grafana-prtg#75]
hello,

I'm using prtg 18.1.36.3728+ ,  on dashboards i can see sensor names but sensor values seems as blank there's no data with sensor, how can i fix this ?

current grafana : v4.6.3 (commit: 7a06a47)

thanks

**Comment by theburakcinar** [comment]
output of api 
xxx.com/api/table.json?username=xxx&passhash=xxx&content=channels&columns=sensor,name&id=8262


{"prtg-version":"18.1.36.3728","treesize":0,"channels":[{"sensor":"","sensor_raw":"","name":"Maximum"},{"sensor":"","sensor_raw":"","name":"Packet Loss"},{"sensor":"","sensor_raw":"","name":"Minimum"},{"sensor":"","sensor_raw":"","name":"Downtime"},{"sensor":"","sensor_raw":"","name":"Ping Time"}]}

**Comment by JohnH77** [comment]
Grafane Restart, Access Rights, username, passhash correct?

you need "content=values"
Example:
api/table.json?content=values&output=json&columns=datetime,value_,coverage&id=8262&noraw=1&usecaption=true

For Testing i use the PRTG API Gui and Live Data 
![grafik](https://user-images.githubusercontent.com/30649081/35379949-266e377c-01b8-11e8-9c10-a0250f5522a7.png)

**Comment by theburakcinar** [comment]
Hi John,

not working ;
Today
custom time ranges
less X minutes
less X hours

working;
last 12 hours -- only working range
last X days
last X years
last X months

source urls (got it via inspect menu on chrome)
https://prtg.local/api/table.json?username=USERNAME&passhash=HASHHH&content=channels&columns=sensor,name&id=8692

https://prtg.local/api/historicdata.xml?username=USERNAME&passhash=HASHHH&id=8686&sdate=2018-01-29-00-00-00&edate=2018-01-30-00-00-00&avg=300&pctshow=false&pctmode=false

**Comment by JohnH77** [comment]
@theburakcinar Can you please try to show a normal ping sensor, works the minutes and houers ranges?

**Comment by JohnH77** [comment]
or maybe try a traffic Sensor

**Comment by theburakcinar** [comment]
tried dev branch now but still same, current values not visible on widgets.

![image](https://user-images.githubusercontent.com/5022026/35511655-d3485a1a-050d-11e8-9663-1561b55988bf.png)

**Comment by alxgrb** [comment]
Hi,
i have a problem with value of PRTG data, with this error **(no data to show)**,but the grafana works!
look at the screenshot please.
![capture-grafana-dashboard](https://user-images.githubusercontent.com/26403641/36092521-f43d4714-0fe7-11e8-84f6-9d3c68c4559f.PNG)

can you help?
Thx

**Comment by theburakcinar** [comment]
what's your prtg version ?

**Comment by alxgrb** [comment]
Prtg version
![grafik](https://user-images.githubusercontent.com/26403641/36245009-1747e410-1229-11e8-95b4-148d16b64410.png)

**Comment by theburakcinar** [comment]
i have problem with 

prtg 18.1.37.13946
 Grafana v5.0.0-beta4 (commit: 1de8891)
