### ISSUE TITLE
I can't finish connection test

### ISSUE THREAD

**Issue by wlsdn0** [neuralfraud/grafana-prtg#77]
Hola senors!

As my subject, I can't finish connection test.

I'm using prtg: V17.4.36.3595, grafana: 4.6.3

I followed wiki

1. added a string to registry key
![image](https://user-images.githubusercontent.com/35521541/35032176-45158370-fba9-11e7-9976-6540f1ed7dff.png)

2. put plugin directory to folder data\plugins
![image](https://user-images.githubusercontent.com/35521541/35032235-8a5291c6-fba9-11e7-963e-f9f0c35265db.png)

3. put datas like this
![image](https://user-images.githubusercontent.com/35521541/35032441-3e873a0c-fbaa-11e7-9766-98153bfc706f.png)

I'm using localhost to initiate PRTG web interface (http not https)

![image](https://user-images.githubusercontent.com/35521541/35032319-daa83108-fba9-11e7-9658-95fc85bb0743.png)

and the account and password I entered is in administration group.

![image](https://user-images.githubusercontent.com/35521541/35032583-ae9a2714-fbaa-11e7-9c26-3123ba3b3ecc.png)

But whenever try connection test, result always same like this
![image](https://user-images.githubusercontent.com/35521541/35032382-13651a4c-fbaa-11e7-9165-69bb553f3382.png)

How can I solve this issue?
I have no idea.

**Comment by minhdt12** [comment]
Use passhash, not password.

**Comment by wlsdn0** [comment]
@minhdt12 Gracias! I solved the issue!
