### ISSUE TITLE
Possible to dispaly only certain info in table of alerts?

### ISSUE THREAD

**Issue by Shadow00Caster** [neuralfraud/grafana-prtg#82]
How would I go about only displaying alerts in a table where the alert is related to disk space.  Within PRTG I can filter by "Tagged With" diskspacesensor and it displays only alerts that are a disk space sensor alert.  Is this something that can be done directly in the query, or possibly through templating?

**Comment by olsonnn** [comment]
Could you please share your query to display the table?

**Comment by Shadow00Caster** [comment]
content=sensors&columns=device,sensor,status,message,downtimesince&filter_status=4

**Comment by olsonnn** [comment]
Try something like this
&filter_type=ping
or
&filter_tag=diskfree

Meanwhile i still cant get a table in Grafana 5.0 :( could you please post more details / settings?

**Comment by Shadow00Caster** [comment]
Got this to work with the query: `content=sensors&columns=device,sensor,status,message,downtimesince&filter_tags=diskspacesensor&filter_status=4&filter_status=5`

This shows warning and critical disk space alerts.

@olsonnn I am just using the example from: https://kb.paessler.com/en/topic/77458-are-there-alternatives-to-maps and am on  Grafana v4.6.3 (commit: 7a06a47)

**Comment by olsonnn** [comment]
@Shadow00Caster not sure why i didn't find this page myself :(
table.xml was my query. should be table.json ! now it works!  thanks a lot!
