### ISSUE TITLE
Get status of a group

### ISSUE THREAD

**Issue by olsonnn** [neuralfraud/grafana-prtg#84]
I want to know the status of a GROUP. not a single sensor.
Looks like this is not possible yet?

When i use the text query method on a group, i always get a value of 3 (ok), even if the group is in warning or error.

**Comment by JohnH77** [comment]
If you want a table with Errors: 
Query Mode
table.json
content=sensors&columns=objid,downtimesince,device,sensor,lastvalue,status,message,priority&filter_status=5&filter_group=GROUP_NAME

or maybe you can use the Business Sensor and then show the Status in Grafana Singlestat
https://www.paessler.com/manuals/prtg/business_process_sensor

![image](https://user-images.githubusercontent.com/30649081/36092015-24df05ee-0fe6-11e8-8b6c-54bdaddec593.png)
![image](https://user-images.githubusercontent.com/30649081/36093167-1ea6244c-0fea-11e8-82d7-7ab06f667795.png)

**Comment by olsonnn** [comment]
@JohnH77 
Thanks for business sensor recommendation! I didn't even knew it exists, but i my case i have over 300 sensors in a group. That's getting complicated. 

The query you have provided does not give any results back. Not in grafana and also not in the prtg api http query. Whatever filter or group with alerts i use.., i don't get any results back. Not sure what's wrong here...

I would be nice if @neuralfraud could implement the group status check

**Comment by JohnH77** [comment]
I dont think that neuralfraud can implement the group Status because it cant be checked with the prtg api, or maybe i just dont know how :)

If you have many devices in one group than maybe this could work: 

metrics: content=sensors&columns=objid,downtimesince,device,sensor,lastvalue,status,message,priority&filter_group=**yourgroup**&filter_status=5

you have to input your group name 

![image](https://user-images.githubusercontent.com/30649081/36102761-98f01b0e-100d-11e8-9b08-2a217d95024d.png)

![image](https://user-images.githubusercontent.com/30649081/36102771-a4b9b2c4-100d-11e8-8e1a-c18ec6593d82.png)

then you can choise the columns that you need

**Comment by JohnH77** [comment]
or you can use the tags filter instead of group filter. 
Example: you create a tag "critical" for your important groups and use
&filter_tags=@tag(critical)

**Comment by olsonnn** [comment]
@JohnH77 
The check in prtg is actually very simple
/api/getobjectstatus.htm?id=9122&name=status   to get a value of 3
/api/getobjectstatus.htm?id=9122&name=status&show=text to get the UP text

9122 is ofcourse the group id.  let me have a look at your other query...

**Comment by olsonnn** [comment]
@JohnH77  found something like this:

The value i'm looking for seems to be found in the  <warnsens_raw> (it's part of the solution)
Now the right query...

    <objid>12477</objid>
    <probe>my probe</probe>
    <group>my group</group>
    <name>my name</name>
    <downsens/>
    <downsens_raw>0000000000</downsens_raw>
    <partialdownsens/>
    <partialdownsens_raw>0000000000</partialdownsens_raw>
    <downacksens/>
    <downacksens_raw>0000000000</downacksens_raw>
    <upsens>&lt;a title=&quot;Tripmonitor: 34x Up&quot; class=&quot;sensorlinkgreen&quot; href=&quot;sensors.htm?id=12477&amp;filter_status=2&amp;filter_status=3&quot;&gt;&lt;div class=&quot;sensg&quot;&gt;34&lt;/div&gt;&lt;/a&gt;</upsens>
    <upsens_raw>0000000034</upsens_raw>
    <warnsens>&lt;a title=&quot;mymonitor: 3x Warning&quot; class=&quot;sensorlinkwarn&quot; href=&quot;sensors.htm?id=12477&amp;filter_status=4&quot;&gt;&lt;div class=&quot;sensy&quot;&gt;3&lt;/div&gt;&lt;/a&gt;</warnsens>
    <warnsens_raw>0000000003</warnsens_raw>

**Comment by olsonnn** [comment]
@JohnH77 
ended up with this in a table for my requested groups. Good enough! and at the end even easier to setup. Thanks for your help

table.json
content=groups&output=json&columns=objid,probe,group,name,downsens,partialdownsens,warnsens&filter_tags=@tag(mytag)
