### ISSUE TITLE
compatibility with grafana 5

### ISSUE THREAD

**Issue by saymonaraujo** [neuralfraud/grafana-prtg#86]
It's working with Grafana 5 (beta 1) ?
Anyone tested ? If not, there's anything that i can do for make it work ?
Thank you :)

**Comment by olsonnn** [comment]
I'm running on 5.0 latest beta1 and apart from this issue https://github.com/neuralfraud/grafana-prtg/issues/85 everything works fine for me.

**Comment by theburakcinar** [comment]
having only 1 problem  https://github.com/neuralfraud/grafana-prtg/issues/75

**Comment by saymonaraujo** [comment]
Thank you guys !
I will try :)
