### ISSUE TITLE
Grafana 5.0 not connecting

### ISSUE THREAD

**Issue by Arthran** [neuralfraud/grafana-prtg#89]
So, trying to set up grafana-prtg for the first time and I keep getting this error:

![Error](https://image.prntscr.com/image/UvOBD0zmRIOWHo_n53lW3A.png)

I'm assuming this is because the plugin hasn't been updated for the 5.0 release (which I believe went live today). I've tried my best to troubleshoot but as you can see the error message isn't helping too much.

Thanks

**Comment by olsonnn** [comment]
things to check:
- passhass (not the password of prtgadmin)
- skip tls / try to run over http as you probably have a self signed cert?

5.0 works fine here

**Comment by neuralfraud** [comment]
People, please just do not use the admin account... Take a minute and create a read-only user with API access and grant that user permission to read all objects. It only takes a minute.
