### ISSUE TITLE
Templating - Grafana 5.0

### ISSUE THREAD

**Issue by saymonaraujo** [neuralfraud/grafana-prtg#90]
Hello, 

I'm a problem with creating a variable in grafana 5.0. Follows a image of the problem:
![1](https://user-images.githubusercontent.com/25465421/37066250-491c3040-2183-11e8-90d6-d6490e3466e2.png)

**Comment by olsonnn** [comment]
Use 
group:*

as query... works fine here

**Comment by saymonaraujo** [comment]
It Worked !
Thank you
