### ISSUE TITLE
Multiplier doesn't seem to work in Dev Plugin

### ISSUE THREAD

**Issue by eter4** [neuralfraud/grafana-prtg#95]
I updated to the Dev version of the plugin and now I can see the Multiplier field.  But no matter what value I put in the graph does not change.   

Is there another step after actually inputting the multiplier value that I need to do? #

**Comment by olsonnn** [comment]
clear your browser cache. I had the same issue. Multiplier values should be green when entering.

**Comment by eter4** [comment]
That fixed it.  I noticed it in green after I cleared the cache.  Good call.  Thanks!

**Comment by isvilenski** [comment]
@olsonnn  thank you. I spend good 4 hours trying to figure why it wasn't working ><
