### ISSUE TITLE
i can't connection test

### ISSUE THREAD

**Issue by kbyou74** [neuralfraud/grafana-prtg#97]
![default](https://user-images.githubusercontent.com/37818435/37942739-916d73c2-31af-11e8-8712-4efb70e7eaf2.PNG)

i'm check regedit and passhash but not connection.. 
please help

**Comment by ThomasRunting** [comment]
Is that ip address for the prtg server correct?

**Comment by huangyingja** [comment]
Hi All,
Since My PRTG version (13.1.2.1462) too old. When test PRTG connection, I got http code 404. 
After checked from PRTG website folder, I found there is no status.json. 
May I know how to resolve it since I saw PRTGAPIService.js also check "getstatus.htm" ?
And PRTG version 13 http://myprtg/API/getstatus.htm existed. 
How to edit " PRTGAPIService.js " to pass the connection testing ?
Thank you ~

**Comment by sergiopizarrou** [comment]
Hi everyone, I'm going to show you how it works:


 **Step 1** 
 Replace " * " String value named "AccessControlAllowOriginHTTPHeader" to the registry key HKLM\Software\Wow6432Node\Paessler\PRTG Network Monitor\Server\Webserver

by 
**http://yourserver/**


![image](https://user-images.githubusercontent.com/39780758/40750629-e5ed5ee0-6435-11e8-9309-e5588e2a80b5.png)

Press OK.

## **Step 2** 

Open PRTG Administration Tool

Change Probe connection Management  to Accept connections from remote probes and all IPs

![image](https://user-images.githubusercontent.com/39780758/40750874-dc8a8034-6436-11e8-922f-1786940bba55.png)


Restart the **PRTG Core Server** service.

![image](https://user-images.githubusercontent.com/39780758/40750902-003b6548-6437-11e8-9c13-0e87882dbdec.png)


**Step 3** get passhash to connect with PRTG api from Grafana.

> example URLs now also contain the credentials for authentication purposes:


 
````
username=myuser&passhash=hash` (or password=mypassword)
````

You can request the passhash for an account with the following API call:


http://**yourserver**/api/getpasshash.htm?username=**myuserhere**&password=**mypasswordhere**

** Replace: your server, myuserhere, mypasswordhere

and paste it on your browser, if it's ok PRTG return **number with a 9 digits** 

**THIS NUMBER IS YOUR PASSHASH** 

2º paste the passhash on your PRTG API Configuration  for your user.
![captura de pantalla 2018-05-30 a la s 18 10 06](https://user-images.githubusercontent.com/39780758/40750276-c1a593dc-6434-11e8-8649-0e2c200c60c3.png)

NOTE:  REMEMBER PASSHASH NOT PASSWORD 


Thank you-

**Comment by niccol** [comment]
I know this is an old issue, but I'm running into the same issue with my install. I've made the changes listed above to PRTG but it still isn't working.

**Comment by neuralfraud** [comment]
> I know this is an old issue, but I'm running into the same issue with my install. I've made the changes listed above to PRTG but it still isn't working.

@niccol Break it until it starts working.

And never use browser access mode
Never use the PRTG admin account 
...dont use localhost... etc. etc.
Please read wiki
